### ISSUE TITLE
Bug 571794: Enable Input parameters for Criteria API SELECT clause

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1034]
Linking to [BZ #571794](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571794)

I noticed a difference in behavior between JPQL and CriteriaBuilder for the allowance of input parameters in the SELECT clause. I'm not sure if this is a bug or a feature, but the code and JPQL behavior implies to me it's a bug even though the JPA Spec seems to indicate this shouldn't work:

```
4.6.4 Input Parameters

    Input parameters can only be used in the WHERE clause or HAVING clause of a query or as the new value for an update item in the SET clause of an update statement.
```

JPQL Example:
```
    Query query = em.createQuery("SELECT s.strVal1, ?1 FROM SimpleEntity s WHERE s.intVal1 = ?2");
    query.setParameter(1, "HELLO");
    query.setParameter(2, 4);
    query.getResultList();
```

This example JPQL does NOT throw an error, instead it generates this SQL query (Oracle, MySQL, Derby, DB2) and runs fine:
```
SELECT STRVAL1, ? FROM SIMPLEENTITY WHERE (INTVAL1 = ?)
	bind => [HELLO, 4]
```

Criteria Builder API Example:
```
    CriteriaBuilder cb = em.getCriteriaBuilder();
    cquery = cb.createQuery(Object[].class);
    root = cquery.from(SimpleEntity.class);
    cquery.multiselect(root.get(SimpleEntity_.strVal1), cb.parameter(String.class, "stringValue"));
    cquery.where(cb.equal(root.get(SimpleEntity_.intVal1), cb.parameter(Long.class, "idValue")));

    query = em.createQuery(cquery);
    query.setParameter("stringValue", "HELLO");
    query.setParameter("idValue", 4);
    query.getResultList();
```

Running this equivalent Criteria API example DOES throw this exception:
```
Exception [EclipseLink-6094] (Eclipse Persistence Services - 2.7.9.qualifier): org.eclipse.persistence.exceptions.QueryException
Exception Description: The parameter name [stringValue] in the query's selection criteria does not match any parameter name defined in the query.
Query: ReportQuery(referenceClass=SimpleEntity sql="SELECT STRVAL1, ? FROM SIMPLEENTITY WHERE (INTVAL1 = ?)")
	at org.eclipse.persistence.exceptions.QueryException.parameterNameMismatch(QueryException.java:1098)
	at org.eclipse.persistence.internal.expressions.ParameterExpression.getValue(ParameterExpression.java:290)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.translate(DatabaseCall.java:1147)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:276)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:334)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:746)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2776)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllReportQueryRows(ExpressionQueryMechanism.java:2713)
	at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:894)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1279)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1845)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482)
```

**Comment by jgrassel** [comment]
Can you put a copy of the issue's text here, instead of just linking to BugZilla?  It makes Eclipselink's github easier to search for issues, and you never know, one day the Eclipse foundation's BugZilla might go away.

**Comment by lukasj** [comment]
>  and you never know, one day the Eclipse foundation's BugZilla might go away

well, it's known it will be deprecated at least (from [the email](https://www.eclipse.org/lists/eclipse.org-committers/msg01247.html)):

> ... in an effort to consolidate, modernize and streamline our infra, we plan on deprecating the usage of Bugzilla, MediaWiki and Git/Gerrit early in 2021, for retirement in late 2022. *By the 2023, we hope that the only two development platforms for Eclipse projects are GitLab and GitHub*. 

 Some projects already [started the move](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540426#c1)
