### ISSUE TITLE
Bug 573435: CriteriaBuilder construct throws argument type mismatch exception with Case Select

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1122]
Linking to [BZ #573435](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573435)

When attempting to execute a CriteriaBuilder query, EclipseLink throws an exception. The equivalent JPQL query executes fine and is currently part of the JSE testing bucket

Example:
```java
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Dto01> cquery = cb.createQuery(Dto01.class);
    Root<EntityTbl01> root = cquery.from(EntityTbl01.class);

    SimpleCase<String, Object> selectCase = cb.selectCase(root.get(EntityTbl01_.itemString2));
    selectCase.when("J", "Japan")
        .otherwise("Other");

    Expression<Long> selectCase2 = cb.<Long>selectCase()
        .when(cb.equal(root.get(EntityTbl01_.itemString3), "C"), new Long(1))
        .otherwise(new Long(0));

    Expression<Long> selectCase3 = cb.<Long>selectCase()
        .when(cb.equal(root.get(EntityTbl01_.itemString4), "D"), new Long(1))
        .otherwise(new Long(0));

    cquery.select(cb.construct(Dto01.class, 
        root.get(EntityTbl01_.itemString1),
        selectCase,
        cb.sum(selectCase2),
        cb.sum(selectCase3)));

    query = em.createQuery(cquery);
    query.getResultList();
```

Exception:
```
    java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.invokeConstructor(PrivilegedAccessHelper.java:489)
	at org.eclipse.persistence.queries.ReportQueryResult.processConstructorItem(ReportQueryResult.java:149)
	at org.eclipse.persistence.queries.ReportQueryResult.buildResult(ReportQueryResult.java:103)
	at org.eclipse.persistence.queries.ReportQueryResult.<init>(ReportQueryResult.java:82)
	at org.eclipse.persistence.queries.ReportQuery.buildObject(ReportQuery.java:598)
	at org.eclipse.persistence.queries.ReportQuery.buildObjects(ReportQuery.java:649)
	at org.eclipse.persistence.queries.ReportQuery.executeDatabaseQuery(ReportQuery.java:852)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:908)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1142)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:460)
```

**Comment by dazey3** [comment]
One idea is to update the result type of the case select expression as WHEN and OTHERWISE clauses are added. This could be a bit messy though if users attempt to set incorrect types. Perhaps some type checking could be done and an error message returned if an invalid type is passed? Not sure if we want to do that or not.
