### ISSUE TITLE
Zero primary key validation on Entity with primary key type "java.lang.Integer" 

### ISSUE THREAD

**Issue by oelprince** [eclipse-ee4j/eclipselink#1149]
When running the code to wildfly version 21.0 and EclipseLink 2.7.8. It throws zero primary key validation exception when the entity has a primary key of zero.

This exception should not happen because the entity primary key type is not primitive type. Its "Integer", which means it can be null. 

Reference doc: https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Basic_JPA_Development/Entities/Ids/Id

Below is the entity primary key definition:

@Id
@Basic(optional = false)
@NotNull
@Column(name = "Lbt_TYP_CD")
private Integer LbtTypCd;

Below is the exception:
Caused by: org.eclipse.persistence.exceptions.ValidationException:
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1) Exception Description: Null or zero primary key encountered in UnitOfWork clone [test.persistence.entity.LbtTyp[ LbtTypCd=0 ]], primary key [0]. Set descriptor's IdValidation or the "eclipselink.id-validation" property.
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.exceptions.ValidationException.nullPrimaryKeyInUnitOfWorkClone(ValidationException.java:1474) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChanges(DeferredChangeDetectionPolicy.java:115) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChangesForExistingObject(DeferredChangeDetectionPolicy.java:61) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:715) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:443) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:975) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.jpa.QueryImpl.performPreQueryFlush(QueryImpl.java:976) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:211) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-ecdf3c32c4]
[0m[0m15:57:16,892 INFO  [stdout] (DefaultMessageListenerContainer-1)         at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-

**Comment by dazey3** [comment]
Hello! Thanks for taking the time to fill out a bug report!

> When running the code to wildly version 21.0 and EclipseLink 2.2.8. It throws zero primary key validation exception when the entity has a primary key of zero.

I don't know what `wildly` is, but in the exception stack you supplied it seems to show that you are executing a query:
```
    [0m[0m15:57:16,892 INFO [stdout] (DefaultMessageListenerContainer-1) at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482) ~[eclipselink-2.7.8.jar!/:2.7.8.v20201217-
```
Can you provide the query and whatever related Entity classes exist?

**Comment by oelprince** [comment]
It's Wildfly application server version 21.0 and eclipse link version 2.7.8
Query: SELECT LBT_TYP_CD, LBT_TYP_DSC_TXT FROM LBT_TYP WHERE (LBT_TYP_CD = ?)
bind => [0]

entities:

@Entity
@Table(name = "LBT_HDR")
public class LbtHdr {

@Id
@Basic(optional = false)
@NotNull
@Column(name = "NTRNL_LBT_HDR")
private Long ntrnlLbtHdr;

@JoinColumn(name = "LBT_TYP_CD", referenceColumnName = "LBT_TYP_CD")
@ManyToOne
private LbtTyp lbtTypCd


}

public class LbtTyp {
   @id
   @basic(optional = false)
   @NotNull
   @column(name = "LBT_TYP_CD")
   private Integer LbtTypCd;
   
  @OneToMany(mappedBy = "lbtTypCd")
  private List<LbtHdr> lbtHdrList;
   
}

**Comment by lukasj** [comment]
EclipseLink, by default, treats `null`/`0` as invalid/unassigned ID. If these values are to be allowed, one has to explicitly set this through the `eclipselink.id-validation` property in `persistence.xml`. See [docs](https://www.eclipse.org/eclipselink/documentation/3.0/jpa/extensions/persistenceproperties_ref.htm#CACEEGCC) for allowed values.

**Comment by oelprince** [comment]
I still believe this should be an issue. If that is the case then the documentation is not accurate, hence, it mentioned specifically that this only apply for primitive types. Integer or Long is not primitive data types.
"Usage

By default, EclipseLink interprets zero as null for **primitive types** that cannot be null (such as int and long), causing zero to be an invalid value for primary keys. You can modify this setting by using the @PrimaryKey annotation to configure an IdValidation for an entity class. Use the eclipselink.id-validation property to configure an IdValidation for the entire persistence unit."

doc reference [https://www.eclipse.org/eclipselink/documentation/3.0/jpa/extensions/annotations_ref.htm#BGEBBFJE](https://www.eclipse.org/eclipselink/documentation/3.0/jpa/extensions/annotations_ref.htm#BGEBBFJE)

**Comment by oelprince** [comment]
I've uploaded code sample that reproduce this issue.
[https://github.com/oelprince/persistence-test](https://github.com/oelprince/persistence-test)

**Comment by lukasj** [comment]
Main has no code to see the exact usecase.

**Comment by oelprince** [comment]
It run as unit test AppTest.java. You can run the code using maven.
mvn clean install

Also, I've added SsnTyp entity with char type id. AppTest2.java add SsnTypCd = '0' and that worked.

**Comment by lukasj** [comment]
My bad, I missed that test. In any case: To make it work, there are following options:
* put `eclipselink.id-validation=NULL` to persistence.xml
* add ` @PrimaryKey(validation = IdValidation.NULL)` to `LbtTyp` entity
* enable weaving
* do not issue flush/commit after running the query or run it w/o transaction (validity depends on the exact context)

**Comment by oelprince** [comment]
I understand that using id-validation property or @Primarkey will make it work. However, I should not have to add these, since I'm not using primitive int or long as my entity Id and instead, I'm using the wrapper classes and in this case, zero should be allowed by default.

I see this as a bug/issue in the current eclipse link code that should be fixed. If you don't see this as an issue then the documentation is not clear because I see the inconsistency between what is in the code and what is in the documentation.

**Comment by lukasj** [comment]
When *weaving is disabled* (which is usually NOT the default on the server), wrappers of int and long primitives in Ids are treated same as primitives.

**Comment by oelprince** [comment]
That is really interesting, after removing the static weaving, I don't see this issue. Wildfly "App server" ran dynamic weaving and I don't see this issue any more. It is strange that the behavior is different when weaving is done statically vs dynamically. Thanks for you help.

**Comment by lukasj** [comment]
`static weaving` means that weaving itself is done during build process, while `dynamic` is done by server during deployment (or by `-javaagent` in case of Java SE environment).  See [the wiki](https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Advanced_JPA_Development/Performance/Weaving/Static_Weaving) on how to set it up.
