### ISSUE TITLE
Bug 573361: Add support for parameters within CriteriaBuilder case/coalesce expressions

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1150]
Linking to [BZ #573361](https://bugs.eclipse.org/bugs/show_bug.cgi?id=573361)

When using parameter markers within CriteriaBuilder case expressions, EclipseLink throws an exception.

Example:
```java
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Object[]> cquery = cb.createQuery(Object[].class);
    Root<SimpleEntity> root = cquery.from(SimpleEntity.class);
    cquery.multiselect(root.get(SimpleEntity_.intVal1));

    ParameterExpression<Integer> checkParam1 = cb.parameter(Integer.class);
    ParameterExpression<Integer> checkParam2 = cb.parameter(Integer.class);
    ParameterExpression<Integer> resultParam1 = cb.parameter(Integer.class);
    ParameterExpression<Integer> resultParam2 = cb.parameter(Integer.class);
    ParameterExpression<Integer> resultParam3 = cb.parameter(Integer.class);

    Expression<Object> selectCase = cb.selectCase()
        .when(cb.equal(root.get(SimpleEntity_.intVal2), checkParam1), resultParam1)
        .when(cb.equal(root.get(SimpleEntity_.intVal2), checkParam2), resultParam2)
        .otherwise(resultParam3);

    cquery.where(cb.equal(root.get(SimpleEntity_.intVal1), selectCase));

    Query query = em.createQuery(cquery);
    query.setParameter(checkParam1, 2);
    query.setParameter(checkParam2, 4);
    query.setParameter(resultParam1, 20);
    query.setParameter(resultParam2, 40);
    query.setParameter(resultParam3, 60);
    query.getResultList();
```

Exception:
```
java.lang.IllegalArgumentException: No parameter with name : Parameter[name=null] was found within the query: ReportQuery(referenceClass=SimpleEntity ).
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:548)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:1)
```

It appears that EclipseLink cannot see the parameter markers being passed into the select Case.

**Comment by dazey3** [comment]
This issue also extends to the coalesce expression as well.

```java
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Object[]> cquery = cb.createQuery(Object[].class);
    Root<SimpleEntity> root = cquery.from(SimpleEntity.class);
    cquery.multiselect(root.get(SimpleEntity_.strVal2));

    ParameterExpression<Integer> intParam1 = cb.parameter(Integer.class);
    CriteriaBuilder.Coalesce<Integer> coalesce = cb.coalesce();
    coalesce.value(root.get(SimpleEntity_.intVal1));
    coalesce.value(intParam1);
    cquery.where(cb.equal(coalesce, root.get(SimpleEntity_.intVal2)));

    query = em.createQuery(cquery);
    query.setParameter(intParam1, 5);
    query.getResultList();
```

Exception:
```
    java.lang.IllegalArgumentException: No parameter with name : Parameter[name=null] was found within the query: ReportQuery(referenceClass=SimpleEntity ).
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:548)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:1)
```
