### ISSUE TITLE
Regression in 2.7.9/3.01: Wrong parameter type expected in "coalesce" in a "exists" subquery

### ISSUE THREAD

**Issue by igormukhin** [eclipse-ee4j/eclipselink#1207]
EclipseLink 2.7.9/3.01
Tested with Oracle, H2

```
String jsql = "select car from Car car"
	+ " where (EXISTS (select c from Country c where car.country = c and COALEASE(c.iso2, :PARAM1) <= 'ME'))";
TypedQuery<Car> query = em.createQuery(jsql, Car.class);
query.setParameter("PARAM1", "DE");
```

This code throws this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: You have attempted to set a value of type class java.lang.String for parameter p1 with expected type of class java.lang.Boolean from query string select car from Car car where (EXISTS (select c from Country c where car.country = c and COALEASE(c.iso2, :PARAM1) <= 'ME')).
	at org.eclipse.persistence.internal.jpa.QueryImpl.setParameterInternal(QueryImpl.java:946)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.setParameter(EJBQueryImpl.java:609)
	at de.wirthedv.test.eclipselink.TestExistsWithCoalesce.test(TestExistsWithCoalesce.java:25)
	at de.wirthedv.test.eclipselink.util.AbstractTestCase.run(AbstractTestCase.java:23)
	at de.wirthedv.test.eclipselink.TestExistsWithCoalesce.main(TestExistsWithCoalesce.java:13)
```

This bug was introduced in version 2.7.5. I tested with 2.7.4 and below, it is working. I tested with 2.7.5, it is failing.

I tried different queries to localize the issue. The issue arises when you have an "exists"-subquery with a set second parameter to "coalesce".

Please advice how to procced.
It is the right place to report a bug?
Should I add a test case in the test suite? How?
Thanks you.

**Comment by igormukhin** [comment]
I think the problematic method should look like this:

```java
    @Override
    public void visit(CoalesceExpression expression) {

        List<Expression> expressions = new ArrayList<Expression>();
        List<Class<?>> types = new LinkedList<Class<?>>();

        // Create the Expression for each scalar expression
        for (org.eclipse.persistence.jpa.jpql.parser.Expression child : expression.getExpression().children()) {
            child.accept(this);
            expressions.add(queryExpression);
            types.add(type[0]);
        }

        // Create the COALESCE expression
        queryExpression = queryContext.getBaseExpression();
        queryExpression = queryExpression.coalesce(expressions);

        // Set the expression type
        type[0] = queryContext.typeResolver().compareCollectionEquivalentTypes(types);
    }
```

I removed the section where it tries to guess parameters types, because:
* In both cases it was implemented incorrectly (in 2.7.4 it was doing nothing, in 2.7.5 it was assigning the wrong type)
* You can't guess a correct type. Even if the type of one of the parameters is known (like `c.iso2` in my example), you still cannot use this type, because the field could use a converter, so the parameter type for another argument would be different.

**Comment by igormukhin** [comment]
Workaround for those who needs to use the newer version of EL -- flip the expression so that the previous type is the correct type.

```java
String jsql = "select c from Country c where c.name is not null and 'DE' != coalesce(c.iso2, :p1)";
```

**Comment by igormukhin** [comment]
I also filed here the bug here https://bugs.eclipse.org/bugs/show_bug.cgi?id=575107
