### ISSUE TITLE
bug when querying an embedded class inside an element collection and commit (without changes)

### ISSUE THREAD

**Issue by geisterdach** [eclipse-ee4j/eclipselink#1455]
There seems to be a fundamental bug when handling with element collections of embeddable:

Short description of the bug:

I query a set of embeddables that are contained in an element collection, then I begin a transaction and commit without changes, I get a NPE.

Detailed description of the bug:

I have two classes (one entity class called "Entity" with id called "id" and one embeddable class called "Embed")

```java
public class Entity {
	private int id;
	private Set<Embed> embeds;
}

public class Embed {
	String property;
}
```

The annotation is the following:

```xml
	<entity class="main.Entity" >
		<attributes>
			<id name="id">
			</id>
			<element-collection name="embeds">
			</element-collection>
		</attributes>
	</entity>

	<embeddable class="main.Embed">
		<attributes>
			<basic name="property">
			</basic>
		</attributes>
	</embeddable>
```

Then I insert some sample data in the DB, with for example the following code:

```java
Entity inputEntity = new Entity();
inputEntity.setId(14);

Embed inputEmbed = new Embed();
inputEmbed.setProperty("prop");

Set<Embed> embeds = new HashSet<Embed>();
embeds.add(inputEmbed);
inputEntity.setEmbeds(embeds);

em.getTransaction().begin();
em.merge(inputEntity);
em.getTransaction().commit();
```
		
Everything works fine so far. Now, I start a different program  (which results in NPE):

```java
TypedQuery<Embed> query = em.createQuery(
				"SELECT y FROM main.Entity x JOIN x.embeds y ",
						Embed.class);
		
List<Embed> embeds = query.getResultList();
		
em.getTransaction().begin();
		
em.getTransaction().commit();
```
		
I get the following error:

```
Exception in thread "main" jakarta.persistence.RollbackException: Exception [EclipseLink-69] (Eclipse Persistence Services - ${release.version}.${build.qualifier}): org.eclipse.persistence.exceptions.DescriptorException

Exception Description: A NullPointerException was thrown while extracting a value from the instance variable [property] in the object [main.Embed].

Internal Exception: java.lang.NullPointerException

Mapping: org.eclipse.persistence.mappings.DirectToFieldMapping[property-->PROPERTY]
Descriptor: RelationalDescriptor(main.Embed --> [])
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:163)
	at main.Main.main(Main.java:53)

Caused by: Exception [EclipseLink-69] (Eclipse Persistence Services - ${release.version}.${build.qualifier}): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: A NullPointerException was thrown while extracting a value from the instance variable [property] in the object [main.Embed].
Internal Exception: java.lang.NullPointerException
Mapping: org.eclipse.persistence.mappings.DirectToFieldMapping[property-->PROPERTY]
Descriptor: RelationalDescriptor(main.Embed --> [])
	at org.eclipse.persistence.exceptions.DescriptorException.nullPointerWhileGettingValueThruInstanceVariableAccessor(DescriptorException.java:1280)
	at org.eclipse.persistence.internal.descriptors.InstanceVariableAttributeAccessor.getAttributeValueFromObject(InstanceVariableAttributeAccessor.java:95)
	at org.eclipse.persistence.mappings.DatabaseMapping.getAttributeValueFromObject(DatabaseMapping.java:691)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.compareObjects(AbstractDirectMapping.java:409)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.compareForChange(AbstractDirectMapping.java:382)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.createObjectChangeSetThroughComparison(DeferredChangeDetectionPolicy.java:197)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.createObjectChangeSet(DeferredChangeDetectionPolicy.java:156)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChanges(DeferredChangeDetectionPolicy.java:98)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChangesForExistingObject(DeferredChangeDetectionPolicy.java:63)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:727)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1582)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:288)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1234)
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:138)
```	
	
	
I use the following versions:

```xml
<dependency>
	<groupId>org.eclipse.persistence</groupId>
	<artifactId>eclipselink</artifactId>
	<version>3.0.2</version>
</dependency>
		
<dependency>
	<groupId>jakarta.persistence</groupId>
	<artifactId>jakarta.persistence-api</artifactId>
	<version>3.0.0</version>
</dependency>
```
	
	
I did some debugging and found out what and why causes the error:

First thing that seems to be odd is that in the commit there are different Embedd Objects which are compared to each other for changes (in the class AbstractDirectMapping in the function compareObjects). In order to compare these objects during the commit the program uses the ClassDescriptor for the Embedded Class "Embed". Especially, it takes the DirectToFieldMapping (for its field "property") in order to access the fields and compare for change. However, if I look at the attributeAccessor of this mapping I observe that "attributeField" is set to NULL.

This ultimatively causes the error in the class InstanceVariableAttributeAccessor Line 83 "return this.attributeField.get(anObject);".
I dont know if an attributeField of an attributeAccessor for an embeddable class should generally be NULL or not.

My questions:
Can this be fixed easily? Is this expected behavior? What are possible workarounds? I tried to query the Entity class (instead of the Embed class)
and iterated of all embeds, this work without errors, even if i modify the embedds and commit the changes.
And the final and most important question for me is are the other bugs when working with element collections of embeddeded classes,
and should element collections of embeddeded be avoided if possible due to buggy behavior?

I would be very happy to hear from you.
Best regards

Test project attached:
[sources.zip](https://github.com/eclipse-ee4j/eclipselink/files/8274747/sources.zip)

**Comment by rhascouet** [comment]
I ran into the same issue.  Hoping this can be fixed

**Comment by ndedobbeleer** [comment]
I encountered the same problem. I was able to get around it by querying each field of the embeddable separately. It's not practical, but it works.

**Comment by StefanBauerTT** [comment]
I just ran into the same issue and can reproduce it with eclipselink 2.7.15 and 4.0.4.

What I find noteworthy is that the actual query is executed fine without an exception being thrown. The exception happens later, when the transaction is being committed and EL tries to compare things to find out if any updates should happen.

So, if you don't use explicit transactions (just omit calling `em.getTransaction().begin()` and `em.getTransaction().commit()`), everything seems to be ok at first glance.

But, in this case, the embeddables **end up in the level 2 cache**. As far as I understand, this should not happen and might be the root cause for this problem.

In our application, I was dealing with a scenario where first we queried the embeddables outside of a transaction, which works. As a side effect, EclipseLink put the embeddables in its L2 cache. Then, the CacheKeys got invalidated somehow. And finally, we removed the embeddable from the ElementCollection of its entity and the entity went to `em.merge()` within a transaction. This lead to the following stacktrace on commit:
```
jakarta.persistence.RollbackException: Exception [EclipseLink-6002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.QueryException
Exception Description: Aggregated objects cannot be written/deleted/queried independently from their owners. 
Descriptor: [RelationalDescriptor(ttstm.jpaplayground.Page --> [])]
Query: ReadObjectQuery(referenceClass=Page )
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:162)
	at ttstm.jpaplayground.HelloApplicationTest.tx(HelloApplicationTest.java:84)
	at ttstm.jpaplayground.HelloApplicationTest.tx(HelloApplicationTest.java:71)
	at ttstm.jpaplayground.HelloApplicationTest.test(HelloApplicationTest.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: Exception [EclipseLink-6002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.QueryException
Exception Description: Aggregated objects cannot be written/deleted/queried independently from their owners. 
Descriptor: [RelationalDescriptor(ttstm.jpaplayground.Page --> [])]
Query: ReadObjectQuery(referenceClass=Page )
	at org.eclipse.persistence.exceptions.QueryException.aggregateObjectCannotBeDeletedOrWritten(QueryException.java:252)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.prepareQuery(ObjectLevelReadQuery.java:2257)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.prepare(ObjectLevelReadQuery.java:2017)
	at org.eclipse.persistence.queries.ReadObjectQuery.prepare(ReadObjectQuery.java:745)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:675)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:970)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:624)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:881)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1195)
	at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:448)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1283)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1823)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1773)
	at org.eclipse.persistence.internal.sessions.AbstractSession.checkAndRefreshInvalidObject(AbstractSession.java:1268)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1070)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1026)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getAndCloneCacheKeyFromParent(UnitOfWorkIdentityMapAccessor.java:211)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getFromIdentityMap(UnitOfWorkIdentityMapAccessor.java:139)
	at org.eclipse.persistence.internal.sessions.IdentityMapAccessor.getFromIdentityMap(IdentityMapAccessor.java:391)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.processDeleteObjectQuery(UnitOfWorkImpl.java:3928)
	at org.eclipse.persistence.queries.DeleteObjectQuery.executeInUnitOfWorkObjectLevelModifyQuery(DeleteObjectQuery.java:110)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:86)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1823)
	at org.eclipse.persistence.mappings.AggregateCollectionMapping.objectRemovedDuringUpdate(AggregateCollectionMapping.java:2345)
	at org.eclipse.persistence.mappings.CollectionMapping.compareObjectsAndWrite(CollectionMapping.java:783)
	at org.eclipse.persistence.mappings.AggregateCollectionMapping.postUpdate(AggregateCollectionMapping.java:2455)
	at org.eclipse.persistence.descriptors.DescriptorQueryManager.postUpdate(DescriptorQueryManager.java:1036)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.updateObjectForWriteWithChangeSet(DatabaseQueryMechanism.java:1177)
	at org.eclipse.persistence.queries.UpdateObjectQuery.executeCommitWithChangeSet(UpdateObjectQuery.java:88)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:326)
	at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:61)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:913)
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:812)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:109)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:86)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1823)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1773)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitChangedObjectsForClassWithChangeSet(CommitManager.java:294)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:152)
	at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4335)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1515)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1605)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:287)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1242)
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:137)
	... 6 more
```

If wanted, I can provide a minimal reproducer for this scenario.

**Comment by StefanBauerTT** [comment]
If anyone comes across the same problem, I found a workaround that prevents that the embeddables are cached by using the query hints `javax.persistence.cache.retrieveMode` and `javax.persistence.cache.storeMode` (or `jakarta.persistence.cache.retrieveMode` and `jakarta.persistence.cache.storeMode` for EclipseLink 4.x) with value `BYPASS`.

Example:

```java
@Entity
public class Book {
	@Id
	String name = "";

	@ElementCollection
	@CollectionTable
	List<Page> pages = Collections.emptyList();

	// further content omitted for brevity
}

@Embeddable
public class Page implements Serializable {
	// further content omitted for brevity
}
```
```java
CriteriaBuilder cb = em.getCriteriaBuilder();
CriteriaQuery<Page> query = cb.createQuery(Page.class);
Root<Book> root = query.from(Book.class);
ListJoin<Book, Page> join = root.join(Book_.pages);
query.select(join);
List<Page> pages = em.createQuery(query)
		.setHint(QueryHints.CACHE_RETRIEVE_MODE, CacheRetrieveMode.BYPASS)
		.setHint(QueryHints.CACHE_STORE_MODE, CacheStoreMode.BYPASS)
		.getResultList();
```
