### ISSUE TITLE
Java 17?

### ISSUE THREAD

**Issue by Clemens85** [eclipse-ee4j/eclipselink#1473]
Hi there,

Sorry for opening an issue here, but maybe it is quite simple to be answered:
Is the current EclipseLink version (3.0 and/or 2.7) also Java 17 compatible?
I saw something about Java 8 / Java 11 compatibility in a release note in EclipseLink 3.0, hence I would assume that it also works with Java 17. But maybe there are some well-known issues or you wouldn't recommend to use EclipseLink with Java 17?

Best regards
Clemens

**Comment by tmakar** [comment]
I have tried to introduce EclipseLink into our project lately and came across a similar issue. I have compiled all source code with Java 17 but at runtime I got the error from EclipseLink that my classes where compiled with an unsupported JDK. I think the latest version of EclipseLink (3.0 / 2.7) was compiled with Java 11, which obviously can't load classes compiled with Java 17. Please correct me if I am wrong.

**Comment by lukasj** [comment]
which version exactly? 2.7.5? 2.7.9? 3.0.0? Latest? The exact version is in the exception log; one can also always run `java -jar eclipselink.jar` or check .jar!/META-INF/MANIFEST.MF to find it if unsure.

If there is a problem with latest 2.7.10 or 3.0.2, feel free to reopen or file new issue 

BTW: those messages are harmless in most cases

**Comment by patric-r** [comment]
With eclipselink 2.7.7 and  OpenJDK 64-Bit Server VM 17.0.4+8, we get:

```
 The java.lang.constant.ConstantDesc class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 0
        at org.eclipse.persistence.internal.libraries.asm.ClassReader.readUnsignedShort(ClassReader.java:3572) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.libraries.asm.ClassReader.<init>(ClassReader.java:200) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:32) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:28) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:24) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.buildClassMetadata(MetadataAsmFactory.java:123) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.getMetadataClass(MetadataAsmFactory.java:177) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAccessibleObject.getMetadataClass(MetadataAccessibleObject.java:73) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataClass.extendsInterface(MetadataClass.java:226) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataClass.extendsInterface(MetadataClass.java:205) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.isCollectionClass(BasicAccessor.java:379) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.processLob(BasicAccessor.java:537) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingConverter(MappingAccessor.java:1850) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingValueConverter(MappingAccessor.java:1875) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.process(BasicAccessor.java:435) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.MetadataDescriptor.processMappingAccessors(MetadataDescriptor.java:1541) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processMappingAccessors(ClassAccessor.java:1658) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processMappingAccessors(EntityAccessor.java:1242) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.process(EntityAccessor.java:701) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1879) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:580) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:629) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2006) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:104) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
        at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:191) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
```

**Comment by nitindang** [comment]
> With eclipselink 2.7.7 and OpenJDK 64-Bit Server VM 17.0.4+8, we get: (User code, including persistence unit has been compiled with java 11 though)
> 
> ```
>  The java.lang.constant.ConstantDesc class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
> java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 0
>         at org.eclipse.persistence.internal.libraries.asm.ClassReader.readUnsignedShort(ClassReader.java:3572) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.libraries.asm.ClassReader.<init>(ClassReader.java:200) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:32) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:28) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.libraries.asm.EclipseLinkClassReader.<init>(EclipseLinkClassReader.java:24) ~[eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.buildClassMetadata(MetadataAsmFactory.java:123) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.getMetadataClass(MetadataAsmFactory.java:177) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAccessibleObject.getMetadataClass(MetadataAccessibleObject.java:73) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataClass.extendsInterface(MetadataClass.java:226) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataClass.extendsInterface(MetadataClass.java:205) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.isCollectionClass(BasicAccessor.java:379) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.processLob(BasicAccessor.java:537) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingConverter(MappingAccessor.java:1850) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingValueConverter(MappingAccessor.java:1875) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.process(BasicAccessor.java:435) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.MetadataDescriptor.processMappingAccessors(MetadataDescriptor.java:1541) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processMappingAccessors(ClassAccessor.java:1658) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processMappingAccessors(EntityAccessor.java:1242) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.process(EntityAccessor.java:701) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1879) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:580) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.deployment.PersistenceUnitProcessor.processORMetadata(PersistenceUnitProcessor.java:629) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2006) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.internal.jpa.deployment.JPAInitializer.callPredeploy(JPAInitializer.java:104) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:107) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
>         at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:191) [eclipselink-2.7.7.jar:2.7.7.v20200504-69f2c2b80d]
> ```

Did you find a fix for this issue ? I am facing the same

**Comment by rfelcman** [comment]
Please use latest 2.7.13 version
https://search.maven.org/artifact/org.eclipse.persistence/eclipselink/2.7.13/jar

**Comment by nitindang** [comment]
Hello @rfelcman , 
Hope u are doing great. 
We were able to resolve the issue by updating the version to 2.7.13. 
But I am facing a weird issue when I am building the war file on a windows platform the application deployed in jboss comes up properly but when I use linux as underlying platform to build war it doesn't.
Please note I am excluding the jpa provided by the JBoss in the deployment descriptor and trying to use the version 2.7.13 packaged by my war file. Any input u have for this ?
JDK used is OpenJDK 17.0.8

**ERROR**
2024-02-23 07:46:26,816 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 62) MSC000001: Failed to start service jboss.persistenceunit."***********": org.jboss.msc.service.StartException in service jboss.persistenceunit."************": javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [***] failed.
Internal Exception: java.lang.IllegalArgumentException: Unsupported api 589824
        at org.jboss.as.jpa@7.4.10.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:198)
        at org.jboss.as.jpa@7.4.10.GA-redhat-00002//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:128)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)

**Comment by rfelcman** [comment]
But it looks like classpath issue. You are mentioning EL  2.7.13, but in the Exception is `Eclipse Persistence Services - 2.7.6.v20200131`. Looks like two EL versions on the classpath? I'm not responsible for a JBoss, but is it configured properly?
Message `Exception Description: Predeployment of PersistenceUnit [**] ` implies, that _persistence.xml_ is not in the right location. In case of WAR `WEB-INF/classes/META-INF`
