### ISSUE TITLE
UUID Generator sometimes doesn't initialize correctly

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1535]
I've noticed this, hit and miss, in my own testing with Eclipselink master (4.0.x) when testing the UUID Generator feature.  Half of the time (after app start) it works , half of the time it doesn't seem to initialize properly and any attempt to use it results in a NullPointerException:

```
junit.framework.AssertionFailedError: 2022-06-03-10:24:00:974 ERROR: Caught exception attempting to call test method testBasicUUIDIdentity_UUID_Generator_JTA_XML on servlet io.openliberty.jpa.tests.jpa31.web.TestUUIDEntityIDServlet 
java.lang.RuntimeException: java.lang.NullPointerException 
at io.openliberty.jpa.tests.jpa31.web.TestUUIDEntityIDServlet.testBasicUUIDIdentity_UUID_Generator_JTA_XML(TestUUIDEntityIDServlet.java:428) 
<snip>
Caused by: java.lang.NullPointerException 
at org.eclipse.persistence.internal.sequencing.SequencingManager.getNextValue(SequencingManager.java:1142) 
at org.eclipse.persistence.internal.sequencing.ClientSessionSequencing.getNextValue(ClientSessionSequencing.java:73) 
at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:435) 
at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:394) 
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.assignSequenceNumber(UnitOfWorkImpl.java:546) 
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNotRegisteredNewObjectForPersist(UnitOfWorkImpl.java:4446) 
at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.registerNotRegisteredNewObjectForPersist(RepeatableWriteUnitOfWork.java:540) 
at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNewObjectForPersist(UnitOfWorkImpl.java:4391) 
at org.eclipse.persistence.internal.jpa.EntityManagerImpl.persist(EntityManagerImpl.java:599) 
at io.openliberty.jpa.tests.jpa31.web.TestUUIDEntityIDServlet.testBasicUUIDIdentity_UUID_Generator_JTA_XML(TestUUIDEntityIDServlet.java:408) 
```

Haven't dug into it yet, but wanted to get this issue on the books.

**Comment by jgrassel** [comment]
Ok, so I've finally broken the ice.  The problem is in org.eclipse.persistence.internal.sequencing.SequencingManager.onConnectSequences(Collection<ClassDescriptor>).  The UUIDGenerator has name "SEQUENCE", which can potentially conflict with TableSequence(SEQUENCE) (because a Sequence has a default name of "SEQUENCE" unless Sequence.setName() is called, if it's not, it stays "SEQUENCE").  Whether the UUIDGenerator works depends on the order sequences get arranged in with the call to `descriptors.iterator()`.  

In the passing scenario, the UUIDGenerator gets processed before the TableSequence:

```
01] Tue, 9 Aug 2022 16:45:57:505 -0500: Enter SequencingManager.onConnectInternal()
01]    this = org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9 (org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9)
01]    descriptors = null (null) 
01]    connectedSequences = null (null) 
01]    project = Project() (org.eclipse.persistence.sessions.Project@271120fa)
02]    
02]    Tue, 9 Aug 2022 16:45:57:505 -0500: Enter SequencingManager.onConnectSequences()
02]       this = org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9 (org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9)
02]       descriptors = null (null) 
02]       connectedSequences = null (null) 
02]       project = Project() (org.eclipse.persistence.sessions.Project@271120fa)
03]       
03]       Tue, 9 Aug 2022 16:45:57:506 -0500: Enter SequencingManager.isConnected()
03]          this = org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9 (org.eclipse.persistence.internal.sequencing.SequencingManager@57024cf9)
03]       
03]       Tue, 9 Aug 2022 16:45:57:506 -0500: Exit SequencingManager.isConnected()
03]          retVal = false (java.lang.Boolean@3f1c821a)
02]    
02]    Tue, 9 Aug 2022 16:45:57:506 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDEmbeddableIdEntity --> [DatabaseTable(XMLUUIDEMBEDDABLEIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@46a937b4)
02]    
02]    Tue, 9 Aug 2022 16:45:57:506 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDEntity --> [DatabaseTable(UUIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@46ca60c9)
02]    
02]    Tue, 9 Aug 2022 16:45:57:506 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDUUIDGenEntity --> [DatabaseTable(UUIDUUIDGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@3ea896d)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  seqName = SEQUENCE (java.lang.String@2dd26f1a)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  sequence = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@22c9e983)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  adding Element :  = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@22c9e983)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.QueryDateTimeEntity --> [DatabaseTable(QUERYDATETIMEENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@3710093b)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.QueryEntity --> [DatabaseTable(QUERYENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@60e64f55)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLEmbeddableUUID_ID --> []) (org.eclipse.persistence.descriptors.RelationalDescriptor@5ef256ec)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDEmbeddableIdEntity --> [DatabaseTable(UUIDEMBEDDABLEIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@331a3940)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.EmbeddableUUID_ID --> []) (org.eclipse.persistence.descriptors.RelationalDescriptor@4f4a7c9)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDIdClassEntity --> [DatabaseTable(XMLUUIDIDCLASSENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@563adce5)
02]    
02]    Tue, 9 Aug 2022 16:45:57:507 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDAutoGenEntity --> [DatabaseTable(UUIDAUTOGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@1a33a5f8)
02]    
02]    Tue, 9 Aug 2022 16:45:57:508 -0500:  seqName = SEQ_GEN (java.lang.String@78814fc7)
02]    
02]    Tue, 9 Aug 2022 16:45:57:508 -0500:  sequence = null (null) 
02]    
02]    Tue, 9 Aug 2022 16:45:57:516 -0500:  adding connectedSequence rcs :  = 0 (java.lang.Integer@4860617c)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  adding connectedSequence dds :  = TableSequence(SEQUENCE) (org.eclipse.persistence.sequencing.TableSequence@2473bdba)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  adding Element :  = DefaultSequence(SEQ_GEN) (org.eclipse.persistence.sequencing.DefaultSequence@57aa443b)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDUUIDGenEntity --> [DatabaseTable(XMLUUIDUUIDGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@2a81b8c4)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  seqName = SEQUENCE (java.lang.String@2dd26f1a)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  sequence = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@22c9e983)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  Noted connectedSequences already contains this sequence :  = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@22c9e983)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDIdClassEntity --> [DatabaseTable(UUIDIDCLASSENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@61a14769)
02]    
02]    Tue, 9 Aug 2022 16:45:57:517 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDEntity --> [DatabaseTable(XMLUUIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@5806a88a)
02]    
02]    Tue, 9 Aug 2022 16:45:57:518 -0500: Exit SequencingManager.onConnectSequences()
02]       connectedSequences = [TableSequence(SEQUENCE), UUIDSequence(SEQUENCE), DefaultSequence(SEQ_GEN)] (java.util.Vector@5d08a42d) {3: TableSequence(SEQUENCE) (org.eclipse.persistence.sequencing.TableSequence@2473bdba), UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@22c9e983), DefaultSequence(SEQ_GEN) (org.eclipse.persistence.sequencing.DefaultSequence@57aa443b) }
```

So because it's processed before the TableSequence (a default sequence in this case), the contains() call below results false, so it doesn't get skipped.

```
                // PERF: Initialize the sequence, this avoid having to look it up every time.
                descriptor.setSequence(sequence);
                if (connectedSequences.contains(sequence)) {
                    JAGDebug.startReportChain().logVariable("Noted connectedSequences already contains this sequence : ", sequence).done();
                    continue;
                }
```

In the failing scenario, the `TableSequence(SEQUENCE)` shows up earlier on the iterator, gets added, and then the contains() matches true for `UUIDSequence(SEQUENCE)`, so it doesn't get added.  Because of that, UUIDGenerator isn't initialized and fails  with the NPE when JPA tries to use it.  This is shown below in the failing scenario:

```
Tue, 9 Aug 2022 16:25:12:312 -0500: Enter SequencingManager.onConnectInternal()
01]    this = org.eclipse.persistence.internal.sequencing.SequencingManager@58722849 (org.eclipse.persistence.internal.sequencing.SequencingManager@58722849)
01]    descriptors = null (null) 
01]    connectedSequences = null (null) 
01]    project = Project() (org.eclipse.persistence.sessions.Project@313bee0a)
02]    
02]    Tue, 9 Aug 2022 16:25:12:312 -0500: Enter SequencingManager.onConnectSequences()
02]       this = org.eclipse.persistence.internal.sequencing.SequencingManager@58722849 (org.eclipse.persistence.internal.sequencing.SequencingManager@58722849)
02]       descriptors = null (null) 
02]       connectedSequences = null (null) 
02]       project = Project() (org.eclipse.persistence.sessions.Project@313bee0a)
03]       
03]       Tue, 9 Aug 2022 16:25:12:312 -0500: Enter SequencingManager.isConnected()
03]          this = org.eclipse.persistence.internal.sequencing.SequencingManager@58722849 (org.eclipse.persistence.internal.sequencing.SequencingManager@58722849)
03]       
03]       Tue, 9 Aug 2022 16:25:12:312 -0500: Exit SequencingManager.isConnected()
03]          retVal = false (java.lang.Boolean@3ed95e5e)
02]    
02]    Tue, 9 Aug 2022 16:25:12:313 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.EmbeddableUUID_ID --> []) (org.eclipse.persistence.descriptors.RelationalDescriptor@24937f11)
02]    
02]    Tue, 9 Aug 2022 16:25:12:313 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDAutoGenEntity --> [DatabaseTable(UUIDAUTOGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@403bb441)
02]    
02]    Tue, 9 Aug 2022 16:25:12:313 -0500:  seqName = SEQ_GEN (java.lang.String@9c2ec6f)
02]    
02]    Tue, 9 Aug 2022 16:25:12:313 -0500:  sequence = null (null) 
02]    
02]    Tue, 9 Aug 2022 16:25:12:323 -0500:  adding connectedSequence rcs :  = 0 (java.lang.Integer@4963a613)
02]    
02]    Tue, 9 Aug 2022 16:25:12:323 -0500:  adding connectedSequence dds :  = TableSequence(SEQUENCE) (org.eclipse.persistence.sequencing.TableSequence@17cfde2e)
02]    
02]    Tue, 9 Aug 2022 16:25:12:323 -0500:  adding Element :  = DefaultSequence(SEQ_GEN) (org.eclipse.persistence.sequencing.DefaultSequence@76b410cb)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.QueryDateTimeEntity --> [DatabaseTable(QUERYDATETIMEENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@55bbfec9)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDEntity --> [DatabaseTable(UUIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@1bc8953)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDEmbeddableIdEntity --> [DatabaseTable(XMLUUIDEMBEDDABLEIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@686b09e4)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDIdClassEntity --> [DatabaseTable(XMLUUIDIDCLASSENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@3e8f7e6a)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLEmbeddableUUID_ID --> []) (org.eclipse.persistence.descriptors.RelationalDescriptor@34c892c4)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDUUIDGenEntity --> [DatabaseTable(UUIDUUIDGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@515b631f)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  seqName = SEQUENCE (java.lang.String@614f74f9)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  sequence = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@24f63a94)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  Noted connectedSequences already contains this sequence :  = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@24f63a94)
02]    
02]    Tue, 9 Aug 2022 16:25:12:324 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDEmbeddableIdEntity --> [DatabaseTable(UUIDEMBEDDABLEIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@5458d27c)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.UUIDIdClassEntity --> [DatabaseTable(UUIDIDCLASSENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@5e111073)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDEntity --> [DatabaseTable(XMLUUIDENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@44635ff4)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.QueryEntity --> [DatabaseTable(QUERYENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@51d4ef76)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  descriptor = RelationalDescriptor(io.openliberty.jpa.tests.jpa31.models.XMLUUIDUUIDGenEntity --> [DatabaseTable(XMLUUIDUUIDGENENTITY)]) (org.eclipse.persistence.descriptors.RelationalDescriptor@430d0c02)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  seqName = SEQUENCE (java.lang.String@614f74f9)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  sequence = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@24f63a94)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500:  Noted connectedSequences already contains this sequence :  = UUIDSequence(SEQUENCE) (org.eclipse.persistence.sequencing.UUIDSequence@24f63a94)
02]    
02]    Tue, 9 Aug 2022 16:25:12:325 -0500: Exit SequencingManager.onConnectSequences()
02]       connectedSequences = [TableSequence(SEQUENCE), DefaultSequence(SEQ_GEN)] (java.util.Vector@15c90e98) {2: TableSequence(SEQUENCE) (org.eclipse.persistence.sequencing.TableSequence@17cfde2e), DefaultSequence(SEQ_GEN) (org.eclipse.persistence.sequencing.DefaultSequence@76b410cb) }
02]    
```

The problem, I think, is the implementation of Sequence.isEquals():

```
    /**
     * INTERNAL:
     * Used in equals.
     */
    public static boolean equalNameAndSize(Sequence seq1, Sequence seq2) {
        if (seq1 == seq2) {
            return true;
        }
        return seq1.getName().equals(seq2.getName()) && (seq1.getPreallocationSize() == seq2.getPreallocationSize());
    }
```

It checks the sequence name (which if two objects are using the default `SEQUENCE` name, of course they'll be equal) and the preallocation size.  It doesn't discriminate between types of sequences.  It doesn't make sense that a TableGenerator should be equal to a UUIDGenerator, even if they have the same sequence name.  If it's the default tablegenerator, it probably has the default preallocation size (50), and UUIDGenerator likely also has the same default prellocation size (50).

**Comment by jgrassel** [comment]
It looks like subclasses of Sequence, like TableSequence, already override `equals()` and include type checking.  That's probably what i need to do with UUIDSequence.
