### ISSUE TITLE
Type conversion error with the Round operation

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1537]
Given entity:

```
@Entity
public class QueryEntity {
    @Id
    private int id;

    private int intVal;
    private long longVal;
    private float floatVal;
    private double doubleVal;
```

The execution of an operation with the round() criteria API operation:
```
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery cq = cb.createQuery(Float.class);
            Root<QueryEntity> root = cq.from(QueryEntity.class);
            cq.select(cb.round(root.get("floatVal"), arg2));
            cq.where(cb.equal(root.get("id"), id));
            Float fResult = (Float) em.createQuery(cq).getSingleResult();
```

results in the following failure:

With Derby:
```
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap') 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryMathFunctionsServlet.testFunction_Round_Criteria(TestNewQueryMathFunctionsServlet.java:463) 
```

With Oracle:
```
java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Float (java.math.BigDecimal and java.lang.Float are in module java.base of loader 'bootstrap') 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryMathFunctionsServlet.testFunction_Round_Criteria(TestNewQueryMathFunctionsServlet.java:463) 

```

The spec says `The ROUND function accepts a numeric argument and an integer argument and returns a number of the same type as the first argument.`, so it should be returning a value of type Float.

**Comment by Tomas-Kraus** [comment]
This should be fixed by the same PR as Issue #1538
