### ISSUE TITLE
EXTRACT failure with Oracle

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1540]
With Oracle (Derby is fine), the following code:
```
// Verify EXTRACT(YEAR) from a LocalDate field
q = em.createQuery("SELECT EXTRACT(YEAR FROM qdte.localDateData) FROM QueryDateTimeEntity qdte WHERE qdte.id = 1");
result = q.getSingleResult();
```

fails with the following Exception:

```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206101604): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLException: ORA-30076: invalid extract field for extract source Error Code: 30076 Call: SELECT EXTRACT(YEAR FROM LOCALDATEDATA) FROM QUERYDATETIMEENTITY WHERE (ID = ?) bind => [1] Query: ReportQuery(referenceClass=QueryDateTimeEntity sql="SELECT EXTRACT(YEAR FROM LOCALDATEDATA) FROM QUERYDATETIMEENTITY WHERE (ID = ?)") 
at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) 
at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:531) at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testEXTRACTFunction_OnQueryResults_JPQL(TestNewQueryTimeFunctionsServlet.java:445) 

```

Similarly, the following:
```
tq = em.createQuery("SELECT qdte FROM QueryDateTimeEntity qdte WHERE EXTRACT(YEAR FROM qdte.localDateData) = 2022", QueryDateTimeEntity.class);
tResList = tq.getResultList();
```
fails with:
```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206101604): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLException: ORA-30076: invalid extract field for extract source Error Code: 30076 Call: SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE (EXTRACT(YEAR FROM LOCALDATEDATA) = ?) bind => [2022] Query: ReadAllQuery(referenceClass=QueryDateTimeEntity sql="SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE (EXTRACT(YEAR FROM LOCALDATEDATA) = ?)") 
at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) 
at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) 
at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483) 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testEXTRACTFunction_InWhereClause_JPQL(TestNewQueryTimeFunctionsServlet.java:565) 
```

**Comment by jgrassel** [comment]
Updated to today's master (https://github.com/eclipse-ee4j/eclipselink/commit/ee55e109584794093f8b89aef7f13cac40daebbb) and still seeing these failures on Oracle.

Using Oracle database:
Version: Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production Version 18.4.0.0.0
Driver: Oracle JDBC driver Version: 21.1.0.0.0

**Comment by dazey3** [comment]
@jgrassel Can you include the DDL for the table generation?

**Comment by Tomas-Kraus** [comment]
I'll run tests with 18c when I'll be back in the office after vacation.

**Comment by Tomas-Kraus** [comment]
This is strange. I run the tests with Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 and got following error:
```
[ERROR]   TestDateTimeFunctions.testIssue1550ExtractIsoWeek:497 » Persistence Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202207261231): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00907: missing right parenthesis

Error Code: 907
Call: SELECT EXTRACT(WEEK FROM DATEVALUE) FROM DATETIMEQUERYENTITY WHERE (ID = ?)
	bind => [1 parameter bound]
Query: ReportQuery(referenceClass=DateTimeQueryEntity sql="SELECT EXTRACT(WEEK FROM DATEVALUE) FROM DATE
```

**Comment by Tomas-Kraus** [comment]
Checking the documentation ... 
[11g](https://docs.oracle.com/cd/E11882_01/server.112/e41084/functions059.htm#SQLRF00639) already contains EXTRACT (datetime), but with limited set of keywords.

**Comment by Tomas-Kraus** [comment]
I did one more test with eclipselink.jdbc.bind-parameters=false but it passed too.
@jgrassel I'm out of ideas how to reproduce/fix this issue.

**Comment by jgrassel** [comment]
Yeah, the problem was user error on my part.  I was using VARCHAR2 on the columns mapped to the java.time types.  I wouldn't expect these functions to operate properly on that.  When I fixed my DDLs to use the proper DATE/TIMESTAMP types, the issue went away. SO I can close this as user error.
