### ISSUE TITLE
CURRENT_TIME reported as invalid identifier with Oracle DB

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1541]
The following query:
```
            TypedQuery<QueryDateTimeEntity> q = em.createQuery("SELECT qdte FROM QueryDateTimeEntity qdte WHERE qdte.localTimeData < LOCAL TIME AND qdte.id <  100",
                                                               QueryDateTimeEntity.class);
            List<QueryDateTimeEntity> resList = q.getResultList();
```

Given entity:
```
@Entity
public class QueryDateTimeEntity {
    @Id
    private int id;

    private java.time.LocalDate localDateData;
    private java.time.LocalTime localTimeData;
    private java.time.LocalDateTime localDateTimeData;
```

fails with the following error when run with Oracle DB:
```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206101604): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00904: "CURRENT_TIME": invalid identifier Error Code: 904 Call: SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALTIMEDATA < CURRENT_TIME) AND (ID < ?)) bind => [100] Query: ReadAllQuery(referenceClass=QueryDateTimeEntity sql="SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALTIMEDATA < CURRENT_TIME) AND (ID < ?))") 
at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) 
at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) 
at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483) 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testLocalTimeFunction_JPQL(TestNewQueryTimeFunctionsServlet.java:202)
```

**Comment by Tomas-Kraus** [comment]
Looks like `CURRENT_TIME` is not known keyword in Oracle database. Will use `CURRENT_TIMESTAMP` and/or `LOCALTIMESTAMP` instead.
