### ISSUE TITLE
LN() failure with SQLServer

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1547]
Looks like SQLServer doesn't have a LN operator, but according to https://docs.microsoft.com/en-us/sql/t-sql/functions/log-transact-sql?view=sql-server-ver16 it sounds like "By default, LOG() returns the natural logarithm".

Observed exception:

```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206151443): org.eclipse.persistence.exceptions.DatabaseException 
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: 'LN' is not a recognized built-in function name. 
Error Code: 195 
Call: SELECT LN(INTVAL) FROM QUERYENTITY WHERE (ID = ?) 
bind => [4] 
Query: ReportQuery(referenceClass=QueryEntity sql="SELECT LN(INTVAL) FROM QUERYENTITY WHERE (ID = ?)") 
at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) 
at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) 
at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:531) 
at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryMathFunctionsServlet.testLNFunction_JPQL(TestNewQueryMathFunctionsServlet.java:318) 
```

JPQL Example:
```
q = em.createQuery("SELECT LN(a.intVal) FROM QueryEntity a WHERE a.id = 4");
        dResult = (double) q.getSingleResult();
        Assert.assertEquals(0.0d, dResult, 0.01);
```

**Comment by Tomas-Kraus** [comment]
MS SQL Server uses LOG function to calculate natural logarithm. Looks like Microsoft must always have something special. :)
