### ISSUE TITLE
DateTime Conversion failure with SQLServer

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1548]
Observed:

```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206151443): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Conversion failed when converting date and/or time from character string. Error Code: 241 Call: SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATETIMEDATA < CURRENT_TIMESTAMP) AND (ID < ?)) bind => [100] Query: ReadAllQuery(referenceClass=QueryDateTimeEntity sql="SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATETIMEDATA < CURRENT_TIMESTAMP) AND (ID < ?))") at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483) at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testLocalDateTimeFunction_JPQL(TestNewQueryTimeFunctionsServlet.java:278) 
```

while executing the following:

```
            Query q = em.createQuery("SELECT qdte FROM QueryDateTimeEntity qdte WHERE qdte.localDateTimeData < LOCAL DATETIME AND qdte.id <  100");
            List resList = q.getResultList();
```

Given entity:
```
@Entity
public class QueryDateTimeEntity {
    @Id
    private int id;

    private java.time.LocalDate localDateData;
    private java.time.LocalTime localTimeData;
    private java.time.LocalDateTime localDateTimeData;
```

**Comment by Tomas-Kraus** [comment]
I did some modifications in SQL server platform to use proper types and casts:
1. SQL to Java type mapping:
```
        classTypeMapping.put("DATETIME2", java.sql.Timestamp.class);
```
3. Java to SQL type mapping:
```
        fieldTypeMapping.put(java.sql.Date.class, new FieldTypeDefinition("DATE", false));
        fieldTypeMapping.put(java.sql.Time.class, new FieldTypeDefinition("TIME", false));
        fieldTypeMapping.put(java.sql.Timestamp.class, new FieldTypeDefinition("DATETIME2", false));
        fieldTypeMapping.put(java.time.LocalDate.class, new FieldTypeDefinition("DATE", false));
        fieldTypeMapping.put(java.time.LocalTime.class, new FieldTypeDefinition("TIME", false));
        fieldTypeMapping.put(java.time.LocalDateTime.class, new FieldTypeDefinition("DATETIME2", false));
        fieldTypeMapping.put(java.time.OffsetTime.class, new FieldTypeDefinition("TIME", false));
        fieldTypeMapping.put(java.time.OffsetDateTime.class, new FieldTypeDefinition("DATETIME2", false));
```
4. MS SQL specific date/time functions
```
        addOperator(ExpressionOperator.simpleFunctionNoParentheses(ExpressionOperator.CurrentDate, "CONVERT(DATE, GETDATE())"));
        addOperator(ExpressionOperator.simpleFunctionNoParentheses(ExpressionOperator.CurrentTime, "CONVERT(TIME, GETDATE())"));
        addOperator(ExpressionOperator.simpleFunctionNoParentheses(ExpressionOperator.LocalDate, "CONVERT(DATE, GETDATE())"));
        addOperator(ExpressionOperator.simpleFunctionNoParentheses(ExpressionOperator.LocalTime, "CONVERT(TIME, GETDATE())"));

```
