### ISSUE TITLE
SQLServer incorrect sql syntax with keyword CURRENT_DATE

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1549]
Observed the following error:

```
 jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202206151443): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'CURRENT_DATE'. Error Code: 156 Call: SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATEDATA < CURRENT_DATE) AND (ID < ?)) bind => [100] Query: ReadAllQuery(referenceClass=QueryDateTimeEntity sql="SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATEDATA < CURRENT_DATE) AND (ID < ?))") at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483) at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testLocalDateFunction_Criteria(TestNewQueryTimeFunctionsServlet.java:339) 
```

Using the following code:
```
            // SELECT qdte FROM QueryDateTimeEntity qdte WHERE qdte.localDateData < LOCAL DATE AND qdte.id <  100"
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery cq = cb.createQuery(QueryDateTimeEntity.class);
            Root<QueryDateTimeEntity> root = cq.from(QueryDateTimeEntity.class);
            cq.select(root);
            cq.where(cb.and(cb.lessThan(root.get("localDateData"), cb.localDate()), cb.lessThan(root.get("id"), 100)));
            TypedQuery<QueryDateTimeEntity> q = em.createQuery(cq);

            List<QueryDateTimeEntity> resList = q.getResultList();
```

With entity:
```
@Entity
public class QueryDateTimeEntity {
    @Id
    private int id;

    private java.time.LocalDate localDateData;
    private java.time.LocalTime localTimeData;
    private java.time.LocalDateTime localDateTimeData;
```

**Comment by Tomas-Kraus** [comment]
Test case is identical to issue 1539 and was already added to the `org.eclipse.persistence.jpa.test.jpql.TestDateTimeFunctions` test suite.
