### ISSUE TITLE
LOCAL DATETIME Query: Oracle Specific Failure: ORA-01830: date format picture ends before converting entire input string

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1572]
Updated to today's version of master (July 5 ee55e109), and encountering the following error when running with Oracle:

```
jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.0.v202207051234): org.eclipse.persistence.exceptions.DatabaseException Internal Exception: java.sql.SQLDataException: ORA-01830: date format picture ends before converting entire input string Error Code: 1830 Call: SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATETIMEDATA < SYSDATE) AND (ID < ?)) bind => [100] Query: ReadAllQuery(referenceClass=QueryDateTimeEntity sql="SELECT ID, LOCALDATEDATA, LOCALDATETIMEDATA, LOCALTIMEDATA FROM QUERYDATETIMEENTITY WHERE ((LOCALDATETIMEDATA < SYSDATE) AND (ID < ?))") 
at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392) 
at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265) 
at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483) 
at io.openliberty.jpa.tests.jpa31.web.TestNewQueryTimeFunctionsServlet.testLocalDateTimeFunction_JPQL(TestNewQueryTimeFunctionsServlet.java:282)
```

Code Involved:
```
            Query q = em.createQuery("SELECT qdte FROM QueryDateTimeEntity qdte WHERE qdte.localDateTimeData < LOCAL DATETIME AND qdte.id <  100");
            List resList = q.getResultList();
```

With entity type:
```
@Entity
public class QueryDateTimeEntity {
    @Id
    private int id;

    private java.time.LocalDate localDateData;
    private java.time.LocalTime localTimeData;
    private java.time.LocalDateTime localDateTimeData;
```

Using Oracle database: 
Version: Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production Version 18.4.0.0.0
Driver: Oracle JDBC driver  Version: 21.1.0.0.0

**Comment by Tomas-Kraus** [comment]
This is strange. I have the [same test](https://github.com/eclipse-ee4j/eclipselink/blob/master/jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestDateTimeFunctions.java#L211) in jse tests and it passes every single build. Tested it on Oracle too.

**Comment by Tomas-Kraus** [comment]
Maybe there is a problem with NLS_DATE_FORMAT. Can you check it?

**Comment by jgrassel** [comment]
No, the problem was because I was using a table definition with VARCHAR2() columns being mapped to the java.time types in the entity.  When I updated the DDL so that the proper DATE/TIMESTAMP column types were being used, the problem resolved itself.  With that said, I feel like I can close this issue as user error.
