### ISSUE TITLE
AUTO for UUID generation does not work

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/eclipselink#1625]
The following test case:

``` java
@Entity
@Table(name = "UUIDAutoGenEntity")
public class UUIDAutoGenEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
}

@Test
public void testBasicUUIDIdentity_AUTO_Generator() {
    EntityManager em = uuidEmf.createEntityManager();
		
    try {
        em.getTransaction().begin();
            
        UUIDAutoGenEntity entity = new UUIDAutoGenEntity();
        entity.setName("Ultron");
        em.persist(entity);
            
        em.getTransaction().commit();
            
        UUID id = entity.getId();
        assertNotNull(id);

    } catch (AssertionError ae) {
        throw ae;
    } catch (Exception e) {
        e.printStackTrace();
        throw new RuntimeException(e);
    } finally {
        if (em.getTransaction().isActive()) {
            em.getTransaction().rollback();
        }
        em.close();
    }
}
```

Fails with the following:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid UUID string: 1
	at org.eclipse.persistence.jpa.test.uuid.TestUUIDGenerator.testBasicUUIDIdentity_AUTO_Generator(TestUUIDGenerator.java:329)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.persistence.jpa.test.framework.EmfRunner.run(EmfRunner.java:43)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 1
	at java.base/java.util.UUID.fromString(UUID.java:215)
	at org.eclipse.persistence.mappings.converters.UUIDConverter.convertDataValueToObjectValue(UUIDConverter.java:58)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.getObjectValue(AbstractDirectMapping.java:626)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:462)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.assignSequenceNumber(ObjectBuilder.java:394)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.assignSequenceNumber(UnitOfWorkImpl.java:546)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNotRegisteredNewObjectForPersist(UnitOfWorkImpl.java:4446)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.registerNotRegisteredNewObjectForPersist(RepeatableWriteUnitOfWork.java:540)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerNewObjectForPersist(UnitOfWorkImpl.java:4391)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.persist(EntityManagerImpl.java:599)
	at org.eclipse.persistence.jpa.test.uuid.TestUUIDGenerator.testBasicUUIDIdentity_AUTO_Generator(TestUUIDGenerator.java:310)
	... 29 more
```

I'm including this test case (deactivated) in an upcoming PR which is adding more UUID testing.

**Comment by dazey3** [comment]
Curiously, persisting with `@GeneratedValue(strategy = GenerationType.UUID)` currently works. According to section 11.1.20 of the 3.1 spec:
```
In the case of a field or property of type java.util.UUID, the AUTO strategy is equivalent to UUID.
```

It seems like that logic needs to be added.

**Comment by jgrassel** [comment]
Integrated into master
