### ISSUE TITLE
2.7.11+: NullPointerException in ExpressionOperator.printCollection (likely concurrency issue)

### ISSUE THREAD

**Issue by jnehlmeier** [eclipse-ee4j/eclipselink#1717]
We received the following NullPointerException in production:

```
java.lang.NullPointerException: Cannot read the array length because "this.argumentIndices" is null
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2391)
	at org.eclipse.persistence.internal.expressions.ArgumentListFunctionExpression.printSQL(ArgumentListFunctionExpression.java:102)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.writeFields(FunctionExpression.java:759)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.writeFieldsFromExpression(SQLSelectStatement.java:2194)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.writeFieldsIn(SQLSelectStatement.java:2209)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.printSQLSelect(SQLSelectStatement.java:1789)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.printSQL(SQLSelectStatement.java:1752)
	at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.printSQLSelectStatement(DatabasePlatform.java:3586)
	at org.eclipse.persistence.platform.database.PostgreSQLPlatform.printSQLSelectStatement(PostgreSQLPlatform.java:543)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.buildCall(SQLSelectStatement.java:868)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.buildCall(SQLSelectStatement.java:879)
	at org.eclipse.persistence.descriptors.ClassDescriptor.buildCallFromStatement(ClassDescriptor.java:885)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.setCallFromStatement(StatementQueryMechanism.java:393)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareReportQuerySelectAllRows(ExpressionQueryMechanism.java:1699)
	at org.eclipse.persistence.queries.ReportQuery.prepareSelectAllRows(ReportQuery.java:1249)
	at org.eclipse.persistence.queries.ReadAllQuery.prepare(ReadAllQuery.java:841)
	at org.eclipse.persistence.queries.ReportQuery.prepare(ReportQuery.java:1117)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:675)
```

The code in question looks like:

```java
if (this.argumentIndices == null) {
    this.argumentIndices = new int[items.size()];
    for (int i = 0; i < this.argumentIndices.length; i++){
        this.argumentIndices[i] = i;
    }
}

String[] dbStrings = getDatabaseStrings(items.size());
for (int i = 0; i < this.argumentIndices.length; i++) { // NPE here
    final int index = this.argumentIndices[I];
    ...
    ...
}
```

The NPE happens in the `for`-loop, so I guess a different Thread has set `this.argumentIndices` to `null` between the `if` statement and the `for` loop.

**Comment by jnehlmeier** [comment]
Issue still exists in EclipseLink 2.7.12.

```
java.lang.NullPointerException: Cannot read the array length because "this.argumentIndices" is null
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2391)
	at org.eclipse.persistence.internal.expressions.ArgumentListFunctionExpression.printSQL(ArgumentListFunctionExpression.java:102)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2400)
	at org.eclipse.persistence.internal.expressions.FunctionExpression.printSQL(FunctionExpression.java:581)
	at org.eclipse.persistence.expressions.ExpressionOperator.printDuo(ExpressionOperator.java:2447)
	at org.eclipse.persistence.internal.expressions.CompoundExpression.printSQL(CompoundExpression.java:291)
	at org.eclipse.persistence.expressions.ExpressionOperator.printDuo(ExpressionOperator.java:2442)
	at org.eclipse.persistence.internal.expressions.CompoundExpression.printSQL(CompoundExpression.java:291)
	at org.eclipse.persistence.internal.expressions.ExpressionSQLPrinter.translateExpression(ExpressionSQLPrinter.java:337)
	at org.eclipse.persistence.internal.expressions.ExpressionSQLPrinter.printExpression(ExpressionSQLPrinter.java:135)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.printSQLWhereClause(SQLSelectStatement.java:1805)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.printSQL(SQLSelectStatement.java:1754)
	at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.printSQLSelectStatement(DatabasePlatform.java:3593)
	at org.eclipse.persistence.platform.database.PostgreSQLPlatform.printSQLSelectStatement(PostgreSQLPlatform.java:543)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.buildCall(SQLSelectStatement.java:868)
	at org.eclipse.persistence.internal.expressions.SQLSelectStatement.buildCall(SQLSelectStatement.java:879)
	at org.eclipse.persistence.descriptors.ClassDescriptor.buildCallFromStatement(ClassDescriptor.java:885)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.setCallFromStatement(StatementQueryMechanism.java:407)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.prepareSelectAllRows(StatementQueryMechanism.java:332)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareSelectAllRows(ExpressionQueryMechanism.java:1724)
	at org.eclipse.persistence.queries.ReadAllQuery.prepareSelectAllRows(ReadAllQuery.java:910)
	at org.eclipse.persistence.queries.ReadAllQuery.prepare(ReadAllQuery.java:841)
	at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:675)
```

The query searches multiple nullable columns for multiple words. To do so it uses `COALESCE` in case the column contains a null value and concatenates search column values using a white space. The resulting string will be searched using `LIKE`.

Consider the search terms "word1" and "word2" then the query would look like
```sql
SELECT e 
FROM Entity e JOIN e.person p
WHERE
  p.id = :personId 
  AND (
    LIKE (LOWER(CONCAT(CONCAT(COALESCE(e.column1, ""), " "), COALESCE(e.column2, ""))), "%word1%")
    AND 
    LIKE (LOWER(CONCAT(CONCAT(COALESCE(e.column1, ""), " "), COALESCE(e.column2, ""))), "%word2%")
  )
```
The query itself is generated using criteria builder. Because criteria builder does not have a varargs method for `concat` it is called twice in code. To demonstrate that in the JPQL equivalent above I used two nested `concat`.

So I guess the issue is similar to issue https://github.com/eclipse-ee4j/eclipselink/issues/1867 and the fix for issue https://github.com/eclipse-ee4j/eclipselink/issues/1354 authored by @dazey3 did not catch all cases.

The issue occurs irregularly so it still seems to be a concurrency issue.

**Comment by jnehlmeier** [comment]
Still happens in 2.7.14 and query did not had `COALESCE` but instead `ORDER BY CASE WHEN ... THEN ... ELSE ... END`.

**Comment by netsrotr** [comment]
Still happens in 2.7.15 
[eclipselink.v2.7.15.stacktrace.txt](https://github.com/user-attachments/files/15612244/eclipselink.v2.7.15.stacktrace.txt)

**Comment by igormukhin** [comment]
I just created a sample project that reproduces the issue:
https://github.com/igormukhin/eclipselink-issue-1717-test

**Comment by igormukhin** [comment]
fixed in 2.7.15

**Comment by netsrotr** [comment]
Any public version we can use for tests of that fix? Any link to a PR?

**Comment by rfelcman** [comment]
> Any public version we can use for tests of that fix? Any link to a PR?

PR #2136
2.7.15 (Javax) download from Maven Central
https://search.maven.org/search?q=g:org.eclipse.persistence%20AND%20v:2.7.15
or e.g.
4.0.5 (Jakarta 10)
https://search.maven.org/search?q=g:org.eclipse.persistence%20AND%20v:4.0.5

**Comment by netsrotr** [comment]
We already use 2.7.15, and as I wrote at [comment](https://github.com/eclipse-ee4j/eclipselink/issues/1717) it still gives the exception. So what exactly you fixed in what version? I would expect to have a version 2.7.16 - we use maven to get the jars, I don't think that there is has calculation over the binaries if you just re-use the same version to publish a fix.

**Comment by igormukhin** [comment]
@netsrotr 
I have a feeling that your issue, although looks similar to this issue, is a different one.

If you open the code for your exception you will see:
```
if ((this.selector == Ref) || ((this.selector == Deref) && (item.isObjectExpression()))) {
    DatabaseTable alias = ((ObjectExpression)item).aliasForTable(((ObjectExpression)item)
            .getDescriptor().getTables().firstElement());  /// your NPE happens here
    printer.printString(alias.getNameDelimited(printer.getPlatform()));
}
```

What was fixed, is NPE in the same method but in a different place. 
Details are here: https://github.com/eclipse-ee4j/eclipselink/issues/2136
I fixed this issue because I needed the fix for my project.
So, my humble advice to you - If you want you problem fixed, provide the fix by yourself. I don't think that core maintainers will fix minor bugs in 2.7.

**Comment by jnehlmeier** [comment]
Yes, this issue here and also described in #2136 is fixed in 2.7.15.
