### ISSUE TITLE
ClassDescriptor.getObjectBuilder() NPE

### ISSUE THREAD

**Issue by szarza** [eclipse-ee4j/eclipselink#1732]
Using Glassfish 6.2.5 in Linux, why might I get the error above?
The error is produced when merging a previous modified object with a ManyToMany relationship....

`Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.persistence.descriptors.ClassDescriptor.getObjectBuilder()" because "descriptor" is null
        at org.eclipse.persistence.internal.sessions.MergeManager.registerObjectForMergeCloneIntoWorkingCopy(MergeManager.java:1062) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.MergeManager.getTargetVersionOfSourceObject(MergeManager.java:239) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.queries.ContainerPolicy.createWrappedObjectFromExistingWrappedObject(ContainerPolicy.java:766) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.mappings.CollectionMapping.mergeIntoObject(CollectionMapping.java:1656) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.descriptors.ObjectBuilder.mergeIntoObject(ObjectBuilder.java:4262) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.MergeManager.mergeChangesOfCloneIntoWorkingCopy(MergeManager.java:612) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.MergeManager.mergeChanges(MergeManager.java:324) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3641) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.mergeCloneWithReferences(RepeatableWriteUnitOfWork.java:403) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.mergeCloneWithReferences(UnitOfWorkImpl.java:3601) ~[org.eclipse.persistence.core.jar:3.0.2]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.mergeInternal(EntityManagerImpl.java:648) ~[org.eclipse.persistence.jpa.jar:3.0.2]
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.merge(EntityManagerImpl.java:625) ~[org.eclipse.persistence.jpa.jar:3.0.2]
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.merge(EntityManagerWrapper.java:280) ~[container-common.jar:?]
        at cestel.atlas.persistence.service.EntityService.save(EntityService.java:129) ~[persistence-2.0.0.jar/:?]
`

**Comment by rfelcman** [comment]
Sorry but without wider context I can't say more.
To simulate this exception we need:

- Test case
or at least to create our test case

- Entity source + target DB object definition
- _persistence.xml_
- code fragment around `em.merge(...)`
