### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: jakarta.persistence.spi.PersistenceUnitInfo while trying to use the -javaagent org.eclipse.persistence.eclipselink_4.0.0.jar

### ISSUE THREAD

**Issue by vogella** [eclipse-ee4j/eclipselink#1803]
We are trying to enable JPA weaving on a Java SE Environment, following the documentation from:

https://www.eclipse.org/eclipselink/documentation/4.0/concepts/concepts.html#APPDEV005
https://www.eclipse.org/eclipselink/documentation/4.0/solutions/solutions.html#TESTINGJPA004
https://www.eclipse.org/eclipselink/documentation/4.0/jpa/extensions/jpa-extensions.html#weaving-2

If we only specify the `-javaagent` option we receive an error :

Command:

````
java  -javaagent:plugins/wrapped.org.eclipse.persistence.eclipselink_4.0.0.jar -jar "plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar" --launcher.library "plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024"-release zak3_beta -environment zak3_test -data @noDefault 
````

Error:
````
Ausnahmebedingung im Thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NoClassDefFoundError: jakarta.persistence.spi.PersistenceUnitInfo
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:358)
        at org.eclipse.persistence.internal.jpa.deployment.JavaSECMPInitializerAgent.initializeFromAgent(JavaSECMPInitializerAgent.java:50)
        at org.eclipse.persistence.internal.jpa.deployment.JavaSECMPInitializerAgent.premain(JavaSECMPInitializerAgent.java:45)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: jakarta.persistence.spi.PersistenceUnitInfo
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
        ... 10 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422

Fatal error: processing of -javaagent failed, processJavaStart failed

````

To get rid of this error we can add  `-Xbootclasspath/a:plugins/jakarta.persistence-api_3.1.0.jar`. 

Full command line:

````
java -Xbootclasspath/a:plugins/jakarta.persistence-api_3.1.0.jar  -javaagent:plugins/wrapped.org.eclipse.persistence.eclipselink_4.0.0.jar -jar "plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar" --launcher.library "plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024" -nl de_CH_ZAK -clearPersistedState -release zak3_beta -environment zak3_test -data @noDefault
````

Is -Xbootclasspathrequired? If yes, I can provide a PR for updating the documentation. If not, why do we see this error?

Even if we specify both options Weaving seems to be inactive, we are still trying to debug this.

**Comment by lukasj** [comment]
Does manifest of `plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar` have the `jakarta.persistence-api.jar` in its `Class-Path` attribute? The documentation assumes that `eclipselink.jar` (and other dependencies) are on the classpath.

**Comment by vogella** [comment]
@lukasj we can try that. For further references, do you have an OSGi or Eclipse RCP example project somewhere which we could use as blueprint?

**Comment by lukasj** [comment]
unfortunately no
