### ISSUE TITLE
[NoClassDefFoundError]: jakarta.persistence.PersistenceException: org/eclipse/persistence/json/JsonPlatform

### ISSUE THREAD

**Issue by skyleaworlder** [eclipse-ee4j/eclipselink#1813]
## version

4.0.0

While it can run on 3.0.3.

## demo

src/main/java/haha/App.java:

<details>

```java
package haha;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;

public class App {
    public static void main( String[] args ) {
        System.out.println( "Hello World!" );

        Record record = new Record();
        record.setMsg("qweqe");

        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("haha");
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        entityManager.getTransaction().begin();
        entityManager.persist(record);
        entityManager.getTransaction().commit();
        entityManager.close();
        entityManagerFactory.close();
    }
}
```

</details>

src/main/java/haha/Record.java:

<details>

```java
package haha;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "record")
public class Record {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String msg;

    public Long getId() {
        return id;
    }

    public String getMsg() {
        return msg;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }
}
```

</details>

src/main/resources/META-INF/persistence.xml:

<details>

```java
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
             version="3.0">
    <persistence-unit name="haha">
        <class>haha.Record</class>
        <properties>
            <property name="jakarta.persistence.jdbc.url" value="jdbc:mysql://localhost:3306/cldiff1"/>
            <property name="jakarta.persistence.jdbc.driver" value="com.mysql.jdbc.Driver"/>
            <property name="jakarta.persistence.jdbc.user" value="root"/>
            <property name="jakarta.persistence.jdbc.password" value="password"/>
            <property name="jakarta.persistence.schema-generation.database.action" value="create"/>
        </properties>
    </persistence-unit>
</persistence>
```

</details>

pom.xml:

<details>

```java
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>edu.fudan.selab</groupId>
  <artifactId>haha</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>haha</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/jakarta.platform/jakarta.jakartaee-api -->
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>10.0.0</version>
      <scope>provided</scope>
    </dependency>

    <!-- https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink -->
    <!-- database -->
    <dependency>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>eclipselink</artifactId>
        <version>4.0.0</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
    <!-- mysql connector -->
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>8.0.32</version>
    </dependency>


  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

</details>

## stack

<details>

```text
/usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java @/tmp/cp_vp1109wwldm1sgidfi15ovf9.argfile haha.App 
Hello World!
[EL Info]: 2023-02-14 15:11:44.477--ServerSession(20853837)--EclipseLink, version: Eclipse Persistence Services - 4.0.0.v202210051929
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[EL Severe]: ejb: 2023-02-14 15:11:44.89--ServerSession(20853837)--java.lang.NoClassDefFoundError: org/eclipse/persistence/json/JsonPlatform
Exception in thread "main" jakarta.persistence.PersistenceException: java.lang.NoClassDefFoundError: org/eclipse/persistence/json/JsonPlatform
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:856)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:221)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getDatabaseSession(EntityManagerFactoryDelegate.java:199)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getDatabaseSession(EntityManagerFactoryImpl.java:534)
        at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactoryImpl(PersistenceProvider.java:153)
        at org.eclipse.persistence.jpa.PersistenceProvider.createEntityManagerFactory(PersistenceProvider.java:191)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
        at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at haha.App.main(App.java:18)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/persistence/json/JsonPlatform
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.eclipse.persistence.platform.database.oracle.json.OracleJsonPlatformProvider.initPlatforms(OracleJsonPlatformProvider.java:38)
        at org.eclipse.persistence.platform.database.oracle.json.OracleJsonPlatformProvider.<clinit>(OracleJsonPlatformProvider.java:33)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.eclipse.persistence.internal.databaseaccess.JsonPlatformManager.getProvider(JsonPlatformManager.java:75)
        at org.eclipse.persistence.internal.databaseaccess.JsonPlatformManager.addProvider(JsonPlatformManager.java:55)
        at org.eclipse.persistence.internal.databaseaccess.JsonPlatformManager.initDirectMap(JsonPlatformManager.java:47)
        at org.eclipse.persistence.internal.databaseaccess.JsonPlatformManager.<init>(JsonPlatformManager.java:99)
        at org.eclipse.persistence.internal.databaseaccess.JsonPlatformManager.getInstance(JsonPlatformManager.java:40)
        at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.getJsonPlatform(DatabasePlatform.java:3858)
        at org.eclipse.persistence.platform.database.MySQLPlatform.buildFieldTypes(MySQLPlatform.java:207)
        at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.getFieldTypes(DatabasePlatform.java:1046)
        at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.getFieldTypeDefinition(DatabasePlatform.java:1038)
        at org.eclipse.persistence.tools.schemaframework.DefaultTableGenerator.getFieldDefFromDBField(DefaultTableGenerator.java:820)
        at org.eclipse.persistence.tools.schemaframework.DefaultTableGenerator.initTableSchema(DefaultTableGenerator.java:308)
        at org.eclipse.persistence.tools.schemaframework.DefaultTableGenerator.generateDefaultTableCreator(DefaultTableGenerator.java:189)
        at org.eclipse.persistence.tools.schemaframework.SchemaManager.getDefaultTableCreator(SchemaManager.java:1016)
        at org.eclipse.persistence.tools.schemaframework.SchemaManager.createDefaultTables(SchemaManager.java:1033)
        at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.generateDefaultTables(EntityManagerFactoryProvider.java:116)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDLToDatabase(EntityManagerSetupImpl.java:4712)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeMetadataDDLToDatabase(EntityManagerSetupImpl.java:4779)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDL(EntityManagerSetupImpl.java:4678)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.writeDDL(EntityManagerSetupImpl.java:4551)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:816)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.persistence.json.JsonPlatform
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 41 more
```

</details>

I wonder if it has something to do with "schemaLocation".

**Comment by rfelcman** [comment]
Hello this bug is fixed in the upcoming 4.0.1. You can verify it against 4.0.1-RC1 .
In case of troubles please let me know here.
