### ISSUE TITLE
Update queries to collections of basic types incorrectly transforms object types

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/eclipselink#1815]
When executing an UpdateQuery, that updates a Collection of basic types (not embeddables), EclipseLink incorrectly transforms the object type. This is particularly bad because the Update query is successfully executed, but when the value is retrieved from the database later, EclipseLink can't properly convert the value back into the expected type.

Entity:
```java
    @Entity
    public class City {
        @Id 
        public String name;
        public Set<Integer> areaCodes;
    }
```

Test:
```java
    Query q = em.createQuery("UPDATE City o SET o.areaCodes=?1 WHERE o.name=?2");
    q.setParameter(1, Set.of(567));
    q.setParameter(2, "Denver");
    q.executeUpdate();
...
    City city = em.find(City.class, "Denver");
```

Exception:
```
Exception Description: Trying to set value [563] for instance variable [areaCodes] of type [java.util.Set] in the object.  The specified object is not an instance of the class or interface declaring the underlying field, or an unwrapping conversion has failed.
Internal Exception: java.lang.IllegalArgumentException: Can not set java.util.Set field test.jakarta.data.jpa.web.City.areaCodes to java.lang.Integer
Mapping: org.eclipse.persistence.mappings.DirectToFieldMapping[areaCodes-->CITY.AREACODES]
Descriptor: RelationalDescriptor(test.jakarta.data.jpa.web.City --> [DatabaseTable(CITY)])
	at org.eclipse.persistence.exceptions.DescriptorException.illegalArgumentWhileSettingValueThruInstanceVariableAccessor(DescriptorException.java:703)
	at org.eclipse.persistence.internal.descriptors.InstanceVariableAttributeAccessor.setAttributeValueInObject(InstanceVariableAttributeAccessor.java:188)
	at org.eclipse.persistence.mappings.DatabaseMapping.setAttributeValueInObject(DatabaseMapping.java:1652)
	at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.buildCloneFromRow(AbstractDirectMapping.java:207)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoWorkingCopyClone(ObjectBuilder.java:2018)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildWorkingCopyCloneFromRow(ObjectBuilder.java:2271)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectInUnitOfWork(ObjectBuilder.java:869)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:756)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:710)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.buildObject(ObjectLevelReadQuery.java:813)
	at org.eclipse.persistence.queries.ReadObjectQuery.registerResultInUnitOfWork(ReadObjectQuery.java:895)
	at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:562)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1183)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:910)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1142)
	at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:441)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1230)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2900)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1866)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1848)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1799)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.executeQuery(EntityManagerImpl.java:915)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.findInternal(EntityManagerImpl.java:858)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:734)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.find(EntityManagerImpl.java:603)
...
Caused by: java.lang.IllegalArgumentException: Can not set java.util.Set field test.jakarta.data.jpa.web.City.areaCodes to java.lang.Integer
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.base/java.lang.reflect.Field.set(Field.java:799)
	at org.eclipse.persistence.internal.descriptors.InstanceVariableAttributeAccessor.setAttributeValueInObject(InstanceVariableAttributeAccessor.java:141)
	... 48 more
```

**Comment by dazey3** [comment]
Digging in deeper, the issue seems to be centered on `org.eclipse.persistence.internal.expressions.QueryKeyExpression.getFieldValue(Object objectValue, AbstractSession session)`. In this method, the object value is meant to be transformed from an object-level value into a database-level value. Except, if the objectValue is a Collection type, then the individual elements in the collection are transformed instead... this creates the issue.

For Inserts/Select queries, the Collection itself is transformed. This means the Collection<E> is serialized into a byte[] for the BLOB/CLOB that is then persisted into the database. However, in `org.eclipse.persistence.internal.expressions.QueryKeyExpression.getFieldValue`, for Update queries, Collection<E> is instead iterated over and each element E is serialized into a byte[].
