### ISSUE TITLE
StackOverflow in MethodVisitorImpl$ELMethodVisitor.visitAttribute

### ISSUE THREAD

**Issue by wilx** [eclipse-ee4j/eclipselink#1895]
I am porting our application to Eclipselink 4.0.1 with Spring Boot 3.0.7, Spring 6.0.9, and Spring Data 2022.0.6. This is from Sproing 2.7.x and Eclipselink 2.7.9. I am getting the follwing stack oveflow due to unbounded recursion. 

It seems to be looping over class `org.springframework.data.jpa.domain.support.AuditingEntityListener`, method `setAuditingHandler`.

Has anyone seen this? Any ideas?

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl.visitAttribute(MethodVisitorImpl.java:508)
	  at org.eclipse.persistence.asm.EclipseLinkMethodVisitor.visitAttribute(EclipseLinkMethodVisitor.java:216)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.MethodVisitorImpl$ELMethodVisitor.visitAttribute(MethodVisitorImpl.java:275)
	  at org.eclipse.persistence.internal.libraries.asm.ClassReader.readMethod(ClassReader.java:1507)
	  at org.eclipse.persistence.internal.libraries.asm.ClassReader.accept(ClassReader.java:744)
	  at org.eclipse.persistence.asm.internal.platform.eclipselink.ClassReaderImpl.accept(ClassReaderImpl.java:63)
	  at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.buildClassMetadata(MetadataAsmFactory.java:104)
	  at org.eclipse.persistence.internal.jpa.metadata.accessors.objects.MetadataAsmFactory.getMetadataClass(MetadataAsmFactory.java:185)
	  at org.eclipse.persistence.internal.jpa.metadata.ORMetadata.getMetadataClass(ORMetadata.java:408)
	  at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.MappedSuperclassAccessor.processEntityListeners(MappedSuperclassAccessor.java:1058)
	  at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processListeners(EntityAccessor.java:1217)
	  at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.addEntityListeners(MetadataProcessor.java:146)
	  at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:677)
	  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:221)
	  - locked <0x409e> (a org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate)
	  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getMetamodel(EntityManagerFactoryDelegate.java:675)
	  at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.getMetamodel(EntityManagerFactoryImpl.java:557)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:568)
	  at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:519)
	  at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:733)
	  at jdk.proxy2.$Proxy185.getMetamodel(Unknown Source:-1)
	  at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean$$Lambda$1249/0x00000008016fa7e8.apply(Unknown Source:-1)
	  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	  at java.util.Iterator.forEachRemaining(Iterator.java:133)
	  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	  at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean.getMetamodels(JpaMetamodelMappingContextFactoryBean.java:94)
	  at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean.createInstance(JpaMetamodelMappingContextFactoryBean.java:68)
	  at org.springframework.data.jpa.repository.config.JpaMetamodelMappingContextFactoryBean.createInstance(JpaMetamodelMappingContextFactoryBean.java:44)
	  at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:142)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$589/0x00000008010b22b8.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  - locked <0x4c7c> (a java.util.concurrent.ConcurrentHashMap)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	  at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365)
	  at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:135)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1682)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$589/0x00000008010b22b8.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:710)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693)
	  at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:133)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:482)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$589/0x00000008010b22b8.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	  at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	  at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:710)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:693)
	  at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:133)
	  at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:482)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	  at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$589/0x00000008010b22b8.getObject(Unknown Source:-1)
	  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	  at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:210)
	  at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:173)
	  at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAsRegistrationBean(ServletContextInitializerBeans.java:168)
	  at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addAdaptableBeans(ServletContextInitializerBeans.java:153)
	  at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:261)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:235)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext$$Lambda$1036/0x000000080143b970.onStartup(Unknown Source:-1)
	  at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:64)
	  at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:53)
	  at org.eclipse.jetty.webapp.Configurations.configure(Configurations.java:514)
	  at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:515)
	  at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1301)
	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:902)
	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:533)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	  at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	  at org.eclipse.jetty.server.Server.start(Server.java:470)
	  at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	  at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	  at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	  at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:123)
	  - locked <0x4c7d> (a java.lang.Object)
	  at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:90)
	  at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:437)
	  at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:179)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:602)
	  - locked <0x4c7e> (a java.lang.Object)
	  at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	  at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	  at org.springframework.boot.test.context.SpringBootContextLoader$$Lambda$339/0x0000000800f27790.getWithException(Unknown Source:-1)
	  at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	  at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	  at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1388)
	  at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545)
	  at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	  at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:184)
	  at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:118)
	  - locked <0x4c7f> (a org.springframework.test.context.cache.DefaultContextCache)
	  at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127)
[...]
```

**Comment by wilx** [comment]
The `readMethod` frame right above the repetition is dealing with

```
attributes = {Attribute@16534} 
 type = "org.aspectj.weaver.MethodDeclarationLineNumber"
```

Is there something wrong with AspectJ attributes?

**Comment by rfelcman** [comment]
It's duplicit with #1832.
Is fixed in snapshots

    Latest snapshot https://jakarta.oss.sonatype.org/content/groups/staging/org/eclipse/persistence/eclipselink/4.0.2-SNAPSHOT/
    or latest 4.0.2 nightly build at https://www.eclipse.org/eclipselink/downloads/nightly.php

4.0.2 will be released next week.
