### ISSUE TITLE
ConcurrentModificationException seen in CollectionContainerPolicy

### ISSUE THREAD

**Issue by vavishal** [eclipse-ee4j/eclipselink#1961]
The following error was intermittently thrown when running the stress test

Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
at java.util.ArrayList$Itr.next(ArrayList.java:861)
at org.eclipse.persistence.internal.queries.InterfaceContainerPolicy.next(InterfaceContainerPolicy.java:301)
at org.eclipse.persistence.internal.queries.ContainerPolicy.next(ContainerPolicy.java:1173)
at org.eclipse.persistence.internal.queries.ContainerPolicy.next(ContainerPolicy.java:1)
at org.eclipse.persistence.internal.oxm.XMLCompositeCollectionMappingNodeValue.marshal(XMLCompositeCollectionMappingNodeValue.java:103)
at org.eclipse.persistence.internal.oxm.NodeValue.marshal(NodeValue.java:149)
at org.eclipse.persistence.internal.oxm.NodeValue.marshal(NodeValue.java:102)
at org.eclipse.persistence.internal.oxm.record.ObjectMarshalContext.marshal(ObjectMarshalContext.java:59)
....

It appears that the access to org/eclipse/persistence/internal/queries/CollectionContainerPolicy is not thread-safe as concurrent access to iteratorFor and addInto method can lead to ConcurrentModificationException

So I have made a fix where in iteratorFor method I am making a clonedList by calling cloneFor method and then returning iterator on that clonedList
In this way, add and iterator method will be independently called on original list and its clonedList respectively and will not cause ConcurrentModificationException

This will be fixed as part of PR https://github.com/eclipse-ee4j/eclipselink/pull/1960

**Comment by rfelcman** [comment]
Cause: Due to incorrect multi-threaded pattern/code when one thread modifies data structure during procession by another thread (Marshaller) leading to ConcurrentModificationException
Action: Every thread should have its own separated input document and should not be shared among the threads as JAXB Mashaller/Unmashaller are not thread safe component and can't be shared across threads
References: https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#other-miscellaneous-topics-performance-and-thread-safety
or
https://javaee.github.io/jaxb-v2/doc/user-guide/ch06.html#d0e6879
