### ISSUE TITLE
JPQL query sets wrong PreparedStatement parameter type for null value on field with @Convert 

### ISSUE THREAD

**Issue by valberico** [eclipse-ee4j/eclipselink#1985]
I am migrating an older project that stores dates as Java Epoch MS in a database bigInt field.
I am also trying make use of JPA AttributeConverter converts between Long and LocalDateTime.

All is good provided a LocalDateTime value is set on the parameter, however when the value is null the parameter set when the PreparedStatement is created uses setNull(index, 93)(timestamp) which causes a type clash since the actual database type is bigint. The issue is obviously the class type cannot be inferred from the null value.
Interestingly, modifying the object after fetching with EntityManager.find does not result in the same error.

Stepping thru the code in the SQLServerPlatform.java class' method 
    public void setParameterValueInDatabaseCall
The conditionals falls thru to:
  } else if (parameter instanceof DatabaseField) {
            setNullFromDatabaseField((DatabaseField)parameter, statement, index);

Since my field uses a converter, the entity field type cannot be used to set the jdbc type when the value is null. Instead, the actual database field type needs to be used.
I have spent a couple days trying to figure out a workaround or some configuration that will prevent this problem.

I want to avoid the use of JPA implementation specific @Annotations but I am open to those.
It seems like during the scan of the entities, the return type of the converter should be used to set the DatabaseField's class type. I set break points and manually set the type to Long.class and was able to successfully set null values via a JPQL update query.

Thanks in advanced to anyone that has a solution.

**Comment by oramattkosem** [comment]
I want to add that AttributeConverters don't seem to be used for JPQL queries at all.  I have a case where an entity has an AttributeConverter applied to it, and the unconverted type is sent directly to the JPA driver (which doesn't understand it).

In my case, I receive an exception like this:
`jakarta.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: incompatible data type in conversion
Error Code: -5561
Call: SELECT t1.id, t1.bigint, t1.boxedBoolean, t1.boxedInt, t1.boxedLong, t1.bytes, t1.category, t1.chars, t1.created, t1.created_by, t1.date, t1.datetime, t1.decimal, t1.locale, t1.primitiveBoolean, t1.primitiveInt, t1.primitiveLong, t1.read_only, t1.string, t1.updated, t1.updated_by, t1.upper_string FROM TEST_ENTITY_CHILD t0, TEST_ENTITY t1 WHERE (t1.id IN (SELECT t2.id FROM TEST_ENTITY t2 WHERE t2.upper_string LIKE ?) AND (t0.parent_id = t1.id)) ORDER BY t1.primitiveInt ASC, t1.string ASC, t0.id DESC
    bind => [STRING B%]
Query: ReadAllQuery(referenceClass=TestEntity sql="SELECT t1.id, t1.bigint, t1.boxedBoolean, t1.boxedInt, t1.boxedLong, t1.bytes, t1.category, t1.chars, t1.created, t1.created_by, t1.date, t1.datetime, t1.decimal, t1.locale, t1.primitiveBoolean, t1.primitiveInt, t1.primitiveLong, t1.read_only, t1.string, t1.updated, t1.updated_by, t1.upper_string FROM TEST_ENTITY_CHILD t0, TEST_ENTITY t1 WHERE (t1.id IN (SELECT t2.id FROM TEST_ENTITY t2 WHERE t2.upper_string LIKE ?) AND (t0.parent_id = t1.id)) ORDER BY t1.primitiveInt ASC, t1.string ASC, t0.id DESC")
    at org.eclipse.persistence.internal.jpa.QueryImpl.getDetailedException(QueryImpl.java:392)
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:265)
    at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:483)
    at test.retail.order.framework.gendeps.jpa.CriteriaQueryFactoryTest.execute(CriteriaQueryFactoryTest.java:547)
    at test.retail.order.framework.gendeps.jpa.CriteriaQueryFactoryTest.testUpperStringSingleValue(CriteriaQueryFactoryTest.java:1229)
    at test.retail.order.framework.gendeps.jpa.CriteriaQueryFactoryTest.testCriteriaQueryFieldTypes(CriteriaQueryFactoryTest.java:420)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: incompatible data type in conversion
Error Code: -5561
Call: SELECT t1.id, t1.bigint, t1.boxedBoolean, t1.boxedInt, t1.boxedLong, t1.bytes, t1.category, t1.chars, t1.created, t1.created_by, t1.date, t1.datetime, t1.decimal, t1.locale, t1.primitiveBoolean, t1.primitiveInt, t1.primitiveLong, t1.read_only, t1.string, t1.updated, t1.updated_by, t1.upper_string FROM TEST_ENTITY_CHILD t0, TEST_ENTITY t1 WHERE (t1.id IN (SELECT t2.id FROM TEST_ENTITY t2 WHERE t2.upper_string LIKE ?) AND (t0.parent_id = t1.id)) ORDER BY t1.primitiveInt ASC, t1.string ASC, t0.id DESC
    bind => [STRING B%]
Query: ReadAllQuery(referenceClass=TestEntity sql="SELECT t1.id, t1.bigint, t1.boxedBoolean, t1.boxedInt, t1.boxedLong, t1.bytes, t1.category, t1.chars, t1.created, t1.created_by, t1.date, t1.datetime, t1.decimal, t1.locale, t1.primitiveBoolean, t1.primitiveInt, t1.primitiveLong, t1.read_only, t1.string, t1.updated, t1.updated_by, t1.upper_string FROM TEST_ENTITY_CHILD t0, TEST_ENTITY t1 WHERE (t1.id IN (SELECT t2.id FROM TEST_ENTITY t2 WHERE t2.upper_string LIKE ?) AND (t0.parent_id = t1.id)) ORDER BY t1.primitiveInt ASC, t1.string ASC, t0.id DESC")
    at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:343)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:702)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:569)
    at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2048)
    at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:611)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:280)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:266)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:352)
    at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:792)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2848)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2801)
    at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:584)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1236)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:913)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1195)
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1283)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1823)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1788)
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:263)
    ... 7 more
Caused by: java.sql.SQLSyntaxErrorException: incompatible data type in conversion
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.setParameter(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.setObject(Unknown Source)
    at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.setParameterValueInDatabaseCall(DatabasePlatform.java:2462)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.prepareStatement(DatabaseCall.java:799)
    at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:630)
    ... 27 more
Caused by: org.hsqldb.HsqlException: incompatible data type in conversion
    at org.hsqldb.error.Error.error(Unknown Source)
    at org.hsqldb.error.Error.error(Unknown Source)
    at org.hsqldb.types.CharacterType.convertToDefaultType(Unknown Source)
    ... 32 more
`

It appears `org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.setParameterValueInDatabaseCall(Object, PreparedStatement, int, AbstractSession)` doesn't consider attribute converters at all, and they don't appear to be considered before parameters reach this method at bind time either.

[My interpretation of the JPA spec suggests that things like this shoul "just work":](https://github.com/jakartaee/persistence/blob/master/spec/src/main/asciidoc/ch03-entity-operations.adoc#type-conversion-of-basic-attributes)
The persistence provider runtime is responsible for invoking the specified conversion methods for the target attribute type when loading the entity attribute from the database and before storing the entity attribute state to the database. The persistence provider must apply any conversion methods to instances of attribute values in path expressions used within Jakarta Persistence query language queries or criteria queries (such as in comparisons, bulk updates, etc.) before sending them to the database for the query execution.

**Comment by oramattkosem** [comment]
@rfelcman That's a great question!  I spent a couple of hours trying to bundle up a test case for the issue I'm seeing, but haven't found success yet.  In my case, a different jar contains an abstract @MappedSuperClass for a given entity and the conversion doesn't work.

I can see that in more basic test cases, org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.getFieldValue(Object, AbstractSession) picks up the task of converting the parameter.  In my failing scenario, that code path is never called.

**Comment by lukasj** [comment]
Having a mappedsuperclass in a different jar is the cause of the failure I believe

**Comment by oramattkosem** [comment]
I took a crack at eliminating that portion of the pattern, replacing it with an interface in the same spot, and the issue persisted.

Unfortunately, upon deeper diving, I uncovered some unsavory reflection code treating a string-like class as a string.  Removing that yields expected behavior.  In my case, it looks like the issue is on our end.  Apologies for any time lost on yours as a result.
