### ISSUE TITLE
JPQL SELECT NEW not joining nor recognising ElementCollection as a collection type

### ISSUE THREAD

**Issue by Riva-Tholoor-Philip** [eclipse-ee4j/eclipselink#2264]
EclipseLink is rejecting JPQL SELECT NEW clauses where an entity contains an attribute that is an ElementCollection.

For example, `SELECT o.comments FROM Rating o WHERE o.id = :id` where the column `comments` is an ElementCollection is correctly returned as a result set.
We can see from the SQL generated by EclipseLink that a JOIN is required to get the data from the `Rating_COMMENTS` table:
```sql
SELECT t1.COMMENTS 
FROM RATING t0 
  LEFT OUTER JOIN Rating_COMMENTS t1 
  ON (t1.Rating_ID = t0.ID) 
WHERE (t0.ID = ?)
```

However, when we try to use `o.comments` in a `SELECT NEW` query like the one below:
```sql
SELECT NEW 
  io.openliberty.jpa.data.tests.models.Rating( o.id, o.item, o.numStars, o.reviewer, o.comments )
FROM Rating o 
WHERE o.id = :id
```

The following error is thrown: 
```txt
Exception [EclipseLink-0] (Eclipse Persistence Services - 5.0.0.v202408071314-43356e84b79e71022b1656a5462b0a72d70787a4): org.eclipse.persistence.exceptions.JPQLException
Exception Description: Problem compiling [SELECT NEW io.openliberty.jpa.data.tests.models.Rating( o.id, o.item, o.numStars, o.reviewer, o.comments ) FROM Rating o WHERE o.id = :id].
[93, 103] The state field path 'o.comments' cannot be resolved to a collection type. (SELECT NEW io.openliberty.jpa.data.tests.models.Rating(o.id, o.item, o.numStars, o.reviewer, [ o.comments ] ...
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:175)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:364)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:298)
at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:180) 
```

I would have expected EclipseLink to be able to satisfy this JPQL query with a SQL Query something like:
```sql
SELECT t0.ID, t0.NAME, t0.PRICE, t0.NUMSTARS, t0.EMAIL, t0.FIRSTNAME, t0.LASTNAME, t1.COMMENTS 
FROM RATING t0
  LEFT OUTER JOIN Rating_COMMENTS t1 
  ON (t1.Rating_ID = t0.ID) 
WHERE (t0ID = ?)
```

**Comment by rfelcman** [comment]
Please attach there entities code.

**Comment by ajaypaul-ibm** [comment]
Hi @rfelcman  Please find the Entity mentioned in the issue below 
```
@Entity
public class Rating {

    @Id
    public int id;

    @Embedded
    public Item item;

    public int numStars;

    @Embedded
    public Reviewer reviewer;

    @ElementCollection(fetch = FetchType.EAGER)
    public Set<String> comments;

    // Basic constructor for builder method
    public Rating() {
    }

    // Test constructor to show that SELECT NEW works without comments field
    public Rating(int id, Item item, int stars, Reviewer reviewer) {
        this.id = id;
        this.item = item;
        this.numStars = stars;
        this.reviewer = reviewer;
        this.comments = null;
    }

    // The constructor SELECT NEW should be able to use
    public Rating(int id, Item item, int stars, Reviewer reviewer, Set<String> comments) {
        this.id = id;
        this.item = item;
        this.numStars = stars;
        this.reviewer = reviewer;
        this.comments = comments;
    }

    public static Rating of(int id, Item item, int stars, Reviewer reviewer, String... comments) {
        Rating inst = new Rating();
        inst.id = id;
        inst.item = item;
        inst.numStars = stars;
        inst.reviewer = reviewer;
        inst.comments = Set.of(comments);
        return inst;
    }

    @Embeddable
    public static class Reviewer {
        public String firstName;
        public String lastName;
        public String email;

        public static Reviewer of(String firstName, String lastName, String email) {
            Reviewer inst = new Reviewer();
            inst.firstName = firstName;
            inst.lastName = lastName;
            inst.email = email;
            return inst;
        }
    }

    @Embeddable
    public static class Item {
        public String name;
        public float price;

        public static Item of(String name, float price) {
            Item inst = new Item();
            inst.name = name;
            inst.price = price;
            return inst;
        }

        @Override
        public String toString() {
            return "Item: " + name + " $" + price;
        }
    }
}

```

**Comment by rfelcman** [comment]
Sorry but, I don't think, that this is bug.
See Jakarta Persistence Specification 3.2 https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a5438

```
constructor_item ::=
    single_valued_path_expression |
    scalar_expression |
    aggregate_expression |
    identification_variable
```

I don't think, that collection or array is allowed as `constructor_item` in any of `single_valued_path_expression | scalar_expression | aggregate_expression | identification_variable`.

**Comment by rfelcman** [comment]
I think, that this issue is duplicitous with #2193

**Comment by ajaypaul-ibm** [comment]
Hi @rfelcman We agree with your comment about the specification. But EclipseLink still appears to have an issue, as it does not reject the usage but instead exhibits unexpected behavior by using only the value of the first element in the collection.

**Comment by ajaypaul-ibm** [comment]
Returning the first element of a collection rather than the whole collection might in some cases lead to a different error being raised due to a mismatch in types. It won't always though.  When you define the record in a way that there isn't a type mismatch, then you get the wrong value. That is a bug.
If you want to see a scenario where it returns wrong data, 
Consider this entity 
```
 public record RomanNumeral(
                String name,
                String romanNumeral,
                Object romanNumeralSymbols

) {


    @Override
    public String toString() {
        StringBuilder s = new StringBuilder();
        s.append(name).append(" ");
        s.append(romanNumeral).append(" ( ");
        s.append(romanNumeralSymbols).append(' ');
        s.append(")");
        return s.toString();
    }
}

```
 And the test :
 ```
@Test
    public void testQueryWithRecordResult() {
        assertEquals(List.of("eleven XI ( X I )",
                             "five V ( V )",
                             "nineteen XIX ( X I X )",
                             "seven VII ( V I I )",
                             "seventeen XVII ( X V I I )",
                             "thirteen XIII ( X I I I )",
                             "three III ( I I I )",
                             "two II ( I I )"),
                     primes.romanNumeralsLessThanEq(20)
                                     .stream()
                                     .map(RomanNumeral::toString)
                                     .collect(Collectors.toList()));
    }
```

When you run the tests, _testQueryWithRecordResult_ of course will fail, but the failure message reveals that EclipseLink is returning a value for the ArrayList<String> attribute, but it isn't a collection of String. It is a single string, seemingly a randomly chosen element of the collection.  That's a bug.
EclipseLink either needs to raise an error indicating it won't support this, or else return the correct value for the Collection attribute. Returning incorrect data is a bug.

**Comment by rfelcman** [comment]
But what is in `testQueryWithRecordResult`? Which JPQL query is there? Last code is different, than what was provided in the origin bug.

**Comment by ajaypaul-ibm** [comment]
@rfelcman Can you try to use the above entity (RomanNumeral) and try to execute query using NEW keyword?

**Comment by rfelcman** [comment]
There is my test case which works well see
`com.oracle.jpa.bugtest.TestRecord#queryNEWTest`
DB is Derby, table (`TEST_TAB_RECORD`) creation script is `init.sql`.
Please check it modify and pass back.
>> `Can you try to use the above entity (RomanNumeral) and try to execute query using NEW keyword?`
`RomanNumeral` is record and can't be Jakarta Persistence `@Entity`.
[JakartaPersistence32POC.tar.gz](https://github.com/user-attachments/files/18408229/JakartaPersistence32POC.tar.gz)

**Comment by ajaypaul-ibm** [comment]
Hi @rfelcman Can you try this modified one JakartaPersistence32POC_modified.zip .  New test called queryNEWTest is added in this.

**Comment by ajaypaul-ibm** [comment]
[JakartaPersistence32POC_modified.zip](https://github.com/user-attachments/files/18409237/JakartaPersistence32POC_modified.zip)

**Comment by rfelcman** [comment]
But if You are mean

```
// Simulate the query for Roman numerals less than or equal to 20
List<RomanNumeral> result = em
                    .createQuery("SELECT r FROM RomanNumeral r WHERE r.value <= :maxValue", RomanNumeral.class)
                    .setParameter("maxValue", 20)
                    .getResultList();
```

from modified tests where

```
package com.oracle.jpa.bugtest;

public record RomanNumeral(
        String name,
        String romanNumeral,
        Object romanNumeralSymbols) {
...
```

it's incorrect as `record RomanNumeral` can't be used as an entity see
specification **2.1. The Entity Class**
https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a18

**Comment by ajaypaul-ibm** [comment]
Hi @rfelcman You are right about the records. I was refering to Jakarta Data test.  Records can be Jakarta Data entities, in which case Jakarta Data creates a separate JPA entity class that is not a record but is based on the record
Can you try to test using below details :
Prime Entity :
```
@Entity
@Table(name = "Prime")
public class Prime {
    @Id
    @Column(nullable = false)
    private int numberId;

    private String name;

    private String romanNumeral;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "Prime_ROMANNUMERALSYMBOLS", joinColumns = @JoinColumn(name = "Prime_NUMBERID"))
    private List<String> romanNumeralSymbols;

    private String binaryDigits;

    @Column(nullable = false)
    private boolean even;

    @Column(nullable = false)
    private int sumOfBits;

    // Getters, setters, and constructors
}
```
Create a DTO like below :
```
public class RomanNumeral {
    private String name;
    private String romanNumeral;
    private List<String> romanNumeralSymbols;

    public RomanNumeral(String name, String romanNumeral, List<String> romanNumeralSymbols) {
        this.name = name;
        this.romanNumeral = romanNumeral;
        this.romanNumeralSymbols = romanNumeralSymbols;
    }

    // Getters and setters
}
```
JPQL Query :
```
TypedQuery<RomanNumeral> query = entityManager.createQuery(
    "SELECT NEW com.example.RomanNumeral(p.name, p.romanNumeral, p.romanNumeralSymbols) " +
    "FROM Prime p WHERE p.numberId <= :numberId ORDER BY p.name", RomanNumeral.class);
query.setParameter("numberId", 20);
List<RomanNumeral> results = query.getResultList();

```
Test case :
```
@Test
public void testRomanNumeralsQuery() {
    EntityManager em = entityManagerFactory.createEntityManager();
    em.getTransaction().begin();

    // Insert sample data into the Prime table
    Prime prime = new Prime(1, "Three", "III", List.of("I", "I", "I"), "11", false, 2);
    em.persist(prime);

    em.getTransaction().commit();

    TypedQuery<RomanNumeral> query = em.createQuery(
        "SELECT NEW com.example.RomanNumeral(p.name, p.romanNumeral, p.romanNumeralSymbols) " +
        "FROM Prime p WHERE p.numberId <= :numberId ORDER BY p.name", RomanNumeral.class);
    query.setParameter("numberId", 1);
    List<RomanNumeral> results = query.getResultList();

    assertEquals(1, results.size());
    assertEquals("Three", results.get(0).getName());
}

```

**Comment by rfelcman** [comment]
But as I mentioned above array or collection is not allowed by Jakarta Persistence spec
https://github.com/eclipse-ee4j/eclipselink/issues/2264#issuecomment-2567718035
`.......p.romanNumeralSymbols) " +`
`private List<String> romanNumeralSymbols;`

**Comment by ajaypaul-ibm** [comment]
Hi @rfelcman , Please find this test below .
  ```
@Test
    public void testElementCollection() throws Exception {
        ECEntity e1 = new ECEntity();
        e1.setId("EC1");
        e1.setIntArray(new int[] { 14, 12, 1 });
        e1.setLongList(new ArrayList<>(List.of(14L, 12L, 1L)));
        e1.setLongListEC(new ArrayList<>(List.of(14L, 12L, 1L)));
        e1.setStringSet(Set.of("fourteen", "twelve", "one"));
        e1.setStringSetEC(Set.of("fourteen", "twelve", "one"));
       
        ECEntity e2 = new ECEntity();
        e2.setId("EC2");
        e2.setIntArray(new int[] { 14, 12, 2 });
        e2.setLongList(new ArrayList<>(List.of(14L, 12L, 2L)));
        e2.setLongListEC(new ArrayList<>(List.of(14L, 12L, 2L)));
        e2.setStringSet(Set.of("fourteen", "twelve", "two"));
        e2.setStringSetEC(Set.of("fourteen", "twelve", "two"));


        tx.begin();
        em.persist(e1);
        em.persist(e2);
        tx.commit();
         // Test JPQL queries
    String jpql;
    List<?> results;
    // Query for intArray
    tx.begin();
    try {
        jpql = "SELECT intArray FROM ECEntity WHERE id=?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC1")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }

    // Query for longList
    tx.begin();
    try {
        jpql = "SELECT longList FROM ECEntity WHERE id=?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC1")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    // Query for stringSet
    tx.begin();
    try {
        jpql = "SELECT stringSet FROM ECEntity WHERE id=?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC1")
                    .getResultList();
        logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    tx.begin();
    try {
        jpql = "SELECT longListEC FROM ECEntity WHERE id=?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC1")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    // Query for longListEC
    tx.begin();
    try {
        jpql = "SELECT longListEC FROM ECEntity WHERE id LIKE ?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC%")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    tx.begin();
    try {
        jpql = "SELECT longList FROM ECEntity WHERE id LIKE ?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC%")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    // Query for stringSetEC
    tx.begin();
    try {
        jpql = "SELECT stringSetEC FROM ECEntity WHERE id LIKE ?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC%")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }
    tx.begin();
    try {
        jpql = "SELECT stringSet FROM ECEntity WHERE id LIKE ?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC%")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }

    tx.begin();
    try {
        jpql = "SELECT stringSetEC FROM ECEntity WHERE id=?1";
        results = em.createQuery(jpql)
                    .setParameter(1, "EC1")
                    .getResultList();
                    logQueryResults(jpql,results);
        tx.commit();
    } catch (Exception e) {
        tx.rollback();
        throw e;
    }

    }
    public void logQueryResults(String jpql, Collection<?> results) {
        System.out.println();
        System.out.println(jpql);
        System.out.println("getResultList returned a " + results.getClass().getTypeName());
        if (!results.isEmpty()) {
            System.out.println("    elements are of type " + results.iterator().next().getClass().getTypeName());
        } else {
            System.out.println("    elements are of type <empty>");
        }
        StringBuilder s = new StringBuilder();
            boolean first = true;
            for (Object element : results) {
                if (first)
                    first = false;
                else
                    s.append(", ");
                if (element instanceof int[])
                    s.append(Arrays.toString((int[]) element));
                else
                    s.append(element);
            }
            System.out.println("            contents are [" + s.toString() + "]");
    }
```

ECEntity.java is like below :
```
package io.openliberty.jpa.data.tests.models;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;

/**
 * Entity with and without ElementCollection attributes.
 */
@Entity
public class ECEntity {

    @Id
    String id;

    int[] intArray = new int[] {};

    ArrayList<Long> longList = new ArrayList<>();

    @ElementCollection(fetch = FetchType.EAGER)
    ArrayList<Long> longListEC = new ArrayList<>();

    Set<String> stringSet = new HashSet<>();

    @ElementCollection(fetch = FetchType.EAGER)
    Set<String> stringSetEC = new HashSet<>();

    public String getId() {
        return id;
    }

    public int[] getIntArray() {
        return intArray;
    }

    public ArrayList<Long> getLongList() {
        return longList;
    }

    public ArrayList<Long> getLongListEC() {
        return longListEC;
    }

    public Set<String> getStringSet() {
        return stringSet;
    }

    public Set<String> getStringSetEC() {
        return stringSetEC;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setIntArray(int[] intArray) {
        this.intArray = intArray;
    }

    public void setLongList(ArrayList<Long> longList) {
        this.longList = longList;
    }

    public void setLongListEC(ArrayList<Long> longListEC) {
        this.longListEC = longListEC;
    }

    public void setStringSet(Set<String> stringSet) {
        this.stringSet = stringSet;
    }

    public void setStringSetEC(Set<String> stringSetEC) {
        this.stringSetEC = stringSetEC;
    }
}
```
This demonstrates that EclipseLink is allowing ElementCollection attributes to be returned by JPQL queries, but with results that are both inconsistent with non-ElementCollection attributes of the same type, and are also incorrect. Especially when returning multiple results which get erroneously combined together into a single collection!

Here is the output of this test. Entity attribute names ending in "EC" use ElementCollection. The others have the same types but don't use ElementCollection:

```
SELECT intArray FROM ECEntity WHERE id=?1
getResultList returned a java.util.Vector
    elements are of type int[]
            contents are [[14, 12, 1]]

SELECT longList FROM ECEntity WHERE id=?1
getResultList returned a java.util.Vector
    elements are of type java.util.ArrayList
            contents are [[14, 12, 1]]

SELECT stringSet FROM ECEntity WHERE id=?1
getResultList returned a java.util.Vector
    elements are of type java.util.ImmutableCollections$SetN
            contents are [[fourteen, twelve, one]]

SELECT longListEC FROM ECEntity WHERE id=?1
getResultList returned a java.util.Vector
    elements are of type java.lang.Long
            contents are [14, 12, 1]

SELECT longListEC FROM ECEntity WHERE id LIKE ?1
getResultList returned a java.util.Vector
    elements are of type java.lang.Long
            contents are [14, 12, 1, 14, 12, 2]

SELECT longList FROM ECEntity WHERE id LIKE ?1
getResultList returned a java.util.Vector
    elements are of type java.util.ArrayList
            contents are [[14, 12, 1], [14, 12, 2]]

SELECT stringSetEC FROM ECEntity WHERE id LIKE ?1
getResultList returned a java.util.Vector
    elements are of type java.lang.String
            contents are [fourteen, twelve, one, fourteen, twelve, two]

SELECT stringSet FROM ECEntity WHERE id LIKE ?1
getResultList returned a java.util.Vector
    elements are of type java.util.ImmutableCollections$SetN
            contents are [[fourteen, twelve, one], [fourteen, twelve, two]]

SELECT stringSetEC FROM ECEntity WHERE id=?1
getResultList returned a java.util.Vector
    elements are of type java.lang.String
            contents are [fourteen, twelve, one]

<<< END: testElementCollecti
```
If EclipseLink wants to reject this outright because the Jakarta Persistence specification does not require element collections to be selected by JPQL queries, that would be perfectly fine. But if EclipseLink doesn't reject it, it at least needs to get the behavior correct and return valid results.

**Comment by ajaypaul-ibm** [comment]
@rfelcman You can refer to this PR https://github.com/OpenLiberty/open-liberty/pull/30578

**Comment by ajaypaul-ibm** [comment]
Moved the recreation details to [2193](https://github.com/eclipse-ee4j/eclipselink/issues/2193),as it better aligns with the issue related to ElementCollection.

**Comment by ajaypaul-ibm** [comment]
Should we close this issue ? @njr-11 @rfelcman

**Comment by rfelcman** [comment]
> Should we close this issue ? [@njr-11](https://github.com/njr-11) [@rfelcman](https://github.com/rfelcman)

From my side yes.

**Comment by njr-11** [comment]
> Should we close this issue ? [@njr-11](https://github.com/njr-11) [@rfelcman](https://github.com/rfelcman)

Yes, given that you said you are now using #2913 instead, it seems fine to me to close this.
