### ISSUE TITLE
Add function version(this) support

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/eclipselink#2305]
Glassfish 8.0.8-M8/Java 21 / Glassfish built-in Derby

Example project: https://github.com/hantsy/jakartaee11-sandbox/tree/master/persistence

The following query:

```sql
SELECT version(this) FROM Employee WHERE email = 'FOObar@gmail.com'
```

Will throw an exception like this. https://github.com/hantsy/jakartaee11-sandbox/actions/runs/11928760798/job/33246272701

```bash
Exception Description: Internal problem encountered while compiling [SELECT version(this) FROM Employee WHERE email = 'FOObar@gmail.com'
].
Internal Exception: java.lang.NullPointerException: Cannot invoke "org.eclipse.persistence.descriptors.VersionLockingPolicy.getVersionMapping()" because the return value of "org.eclipse.persistence.descriptors.ClassDescriptor.getOptimisticLockingPolicy()" is null
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1848)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1869)
	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.createQuery(EntityManagerWrapper.java:472)
	at com.example.it.EmployeeTest.testEmployeeCurd(EmployeeTest.java:141)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.arquillian.junit5.ArquillianExtension.interceptTestMethod(ArquillianExtension.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: Exception [EclipseLink-0] (Eclipse Persistence Services - 5.0.0-B03.v202409121024-4a7149f0cd04d7466837d70f68abb743c88acb83): org.eclipse.persistence.exceptions.JPQLException
Exception Description: Internal problem encountered while compiling [SELECT version(this) FROM Employee WHERE email = 'FOObar@gmail.com'
].
Internal Exception: java.lang.NullPointerException
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildUnexpectedException(HermesParser.java:221)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:316)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:180)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:144)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:120)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:107)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:91)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1846)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.eclipse.persistence.internal.jpa.jpql.JPQLFunctionsAbstractBuilder.visit(JPQLFunctionsAbstractBuilder.java:89)
	at org.eclipse.persistence.jpa.jpql.parser.VersionExpression.accept(VersionExpression.java:47)
	at org.eclipse.persistence.internal.jpa.jpql.ReadAllQueryBuilder.visit(ReadAllQueryBuilder.java:132)
	at org.eclipse.persistence.jpa.jpql.parser.SelectClause.accept(SelectClause.java:42)
	at org.eclipse.persistence.internal.jpa.jpql.ReadAllQueryBuilder.visit(ReadAllQueryBuilder.java:138)
	at org.eclipse.persistence.jpa.jpql.parser.SelectStatement.accept(SelectStatement.java:100)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser$DatabaseQueryVisitor.buildReadAllQuery(HermesParser.java:389)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser$DatabaseQueryVisitor.visit(HermesParser.java:439)
	at org.eclipse.persistence.jpa.jpql.parser.SelectStatement.accept(SelectStatement.java:100)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser$DatabaseQueryVisitor.visit(HermesParser.java:429)
	at org.eclipse.persistence.jpa.jpql.parser.JPQLExpression.accept(JPQLExpression.java:203)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:302)
	... 13 more

```

**Comment by rfelcman** [comment]
In the attachment is my local test case. See `com.oracle.jpa.bugtest.TestIdVersionJPQL#queryVERSION6WithThisTest` plus `com.oracle.jpa.bugtest.IdVersionEntity` . This test case works to me without any issue.
Test table `TEST_TAB_IDVERSION` DDL is available in _init.sql_ script. Default DB is Apache Derby which shoud be started in the project by `mvn derby:run` .

[JakartaPersistence32POC.tar.gz](https://github.com/user-attachments/files/17827798/JakartaPersistence32POC.tar.gz)

**Comment by hantsy** [comment]
@rfelcman I found it was my fault. 

I forget to add `@Version` field in this entity. But it should throw a friendly exception message to indicate that.
