### ISSUE TITLE
ConcurrencyException "Max number of attempts to lock object" in WriteLockManager

### ISSUE THREAD

**Issue by alex-mavr** [eclipse-ee4j/eclipselink#2319]
**Describe the bug**
When using second-level cache on eclipselink version 4.0.3 (and on) we occusionally get the following exception

```
Exception [EclipseLink-2007] (Eclipse Persistence Services - 4.0.3.v202405220658): org.eclipse.persistence.exceptions.ConcurrencyException
Exception Description: Max number of attempts to lock object: User{id=-1, name='user', email='user@mail.com', addresses=0} exceeded.  Failed to clone the object.
	at org.eclipse.persistence.exceptions.ConcurrencyException.maxTriesLockOnCloneExceded(ConcurrencyException.java:62)
	at org.eclipse.persistence.internal.helper.WriteLockManager.acquireLocksForClone(WriteLockManager.java:204)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1068)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1026)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getAndCloneCacheKeyFromParent(UnitOfWorkIdentityMapAccessor.java:211)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkIdentityMapAccessor.getFromIdentityMap(UnitOfWorkIdentityMapAccessor.java:139)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4135)
	at org.eclipse.persistence.queries.ObjectBuildingQuery.registerIndividualResult(ObjectBuildingQuery.java:466)
	at org.eclipse.persistence.queries.ReadObjectQuery.registerResultInUnitOfWork(ReadObjectQuery.java:898)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkEarlyReturn(ObjectLevelReadQuery.java:949)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:850)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1195)
	at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:448)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1283)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1841)
```
		
In version 4.0.2 (and older) we get no such exception.
The issue seems to be related to  #2118
https://github.com/eclipse-ee4j/eclipselink/pull/2118/commits/120511bec8de3e0473d97abaacbc984331467533#diff-feb6a6b57e86e1e75038ef21b8840c8eb0d713ea82d66205ffea78d02211a4edL170

**To Reproduce**
1. Clone project https://github.com/alex-mavr/eclipselink-error-2007
2. Run EclipseLinkBugTest#testConcurrentException unit test (you may need to increase the value of ITERATIONS constant)

Unit test must fail with the stack trace above

**Expected behavior**
Should be able to acquire lock to perform query

**Comment by cserepj** [comment]
I am seeing complete deadlocks with 4.0.4 and similar exceptions, downgrading to 4.0.2 was only what helped.

**Comment by rfelcman** [comment]
I'd like ask You which Java/JDK is used?

**Comment by cserepj** [comment]
JDK23 from docker image jetty:12-jdk23

**Comment by cserepj** [comment]
And 4.0.3 seems to also be unaffected.

**Comment by alex-mavr** [comment]
> I'd like ask You which Java/JDK is used?

I've reproduced it on RHEL 8.9 with OpenJDK build  `17.0.9+9-LTS` and on Win11 with Oracle JDK build `17.0.12+8-LTS-296`

**Comment by rfelcman** [comment]
First release candidate of EclipseLink 4.0.5 (4.0.5-RC1) is available.
You can download it from usual sources like:
Maven Central
Milestone builds: https://download.eclipse.org/rt/eclipselink/milestones/4.0.5/RC1/
List of changes against 4.0.4 is available at: https://github.com/eclipse-ee4j/eclipselink/releases/tag/4.0.5-RC1

**Comment by alex-mavr** [comment]
Indeed, the UTs pass. Thank you for the quick fix
