### ISSUE TITLE
JPQL query can not be parsed in Turkish locale

### ISSUE THREAD

**Issue by andreysubbotin** [eclipse-ee4j/eclipselink#345]
if the query contains LIKE or IS NULL condition, it can not be executed in Turkish locale. 
Project with test: `com.company.jpa.QueryTest`
[test-jpa.zip](https://github.com/eclipse-ee4j/eclipselink/files/2712256/test-jpa.zip)

Error: 
```
Exception Description: Syntax error parsing [select u from sec$User u where u.loginLowerCase like :login]. 
[31, 59] The expression is not a valid conditional expression.
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:155)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.validate(HermesParser.java:334)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.populateQueryImp(HermesParser.java:278)
	at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildQuery(HermesParser.java:163)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:142)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.buildEJBQLDatabaseQuery(EJBQueryImpl.java:116)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:102)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.<init>(EJBQueryImpl.java:86)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1614)
	... 27 more
```

**Comment by lukasj** [comment]
fixed in master and 2.7.5
