### ISSUE TITLE
Exception when using ScrollableCursor with ResultSetType.ForwardOnly and DB2 (z/OS)

### ISSUE THREAD

**Issue by NiklasMehner** [eclipse-ee4j/eclipselink#484]
We are using QueryDSL with eclipselink (in Websphere Liberty) backed by a DB2 (z/OS) database.

In `com.querydsl.jpa.EclipseLinkHandler` the following code is used to create a cursor:

`JpaQuery<T> elQuery = (JpaQuery<T>) query;
elQuery.setHint(QueryHints.RESULT_SET_TYPE, ResultSetType.ForwardOnly);
elQuery.setHint(QueryHints.SCROLLABLE_CURSOR, true);
final Cursor cursor = elQuery.getResultCursor();`

When using this with DB2 we get the exception:

`
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.ibm.db2.jcc.am.SqlException: [jcc][t4][10179][10900][3.67.27] This method should only be called on ResultSet objects that are scrollable (type TYPE_SCROLL_SENSITIVE or TYPE_SCROLL_INSENSITIVE). ERRORCODE=-4476, SQLSTATE=null
Error Code: -4476
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1650)
	at org.eclipse.persistence.queries.ScrollableCursor.isAfterLast(ScrollableCursor.java:318)
	at org.eclipse.persistence.queries.ScrollableCursor.getPosition(ScrollableCursor.java:244)
	at org.eclipse.persistence.queries.ScrollableCursor.retrieveNextObject(ScrollableCursor.java:553)
	at org.eclipse.persistence.queries.ScrollableCursor.loadNext(ScrollableCursor.java:413)
	at org.eclipse.persistence.queries.ScrollableCursor.hasNext(ScrollableCursor.java:279)
	at com.querydsl.jpa.TransformingIterator.hasNext(TransformingIterator.java:52)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:56)
	at com.querydsl.core.group.GroupByMap.transform(GroupByMap.java:35)
	at com.querydsl.core.support.FetchableQueryBase.transform(FetchableQueryBase.java:55)
Caused by: com.ibm.db2.jcc.am.SqlException: [jcc][t4][10179][10900][3.67.27] This method should only be called on ResultSet objects that are scrollable (type TYPE_SCROLL_SENSITIVE or TYPE_SCROLL_INSENSITIVE). ERRORCODE=-4476, SQLSTATE=null
	at com.ibm.db2.jcc.am.gd.a(gd.java:733)
	at com.ibm.db2.jcc.am.gd.a(gd.java:66)
	at com.ibm.db2.jcc.am.gd.a(gd.java:128)
	at com.ibm.db2.jcc.am.ResultSet.checkThatResultSetTypeIsScrollable(ResultSet.java:4569)
	at com.ibm.db2.jcc.am.ResultSet.isAfterLast(ResultSet.java:1906)
	at org.eclipse.persistence.queries.ScrollableCursor.isAfterLast(ScrollableCursor.java:316)
	... 62 more
`

So `ScrollableCursor` calls `ResultSet.isAfterLast` while the documentation of isAfterLast states:

Note: Support for the 'isAfterLast' method is optional for 'ResultSet's with a result set type of 'TYPE_FORWARD_ONLY'.

So when created with ResultSetType.ForwardOnly ScrollableCursor should not use isAfterLast while getting the current position.

**Comment by rdicroce** [comment]
This is a bug in QueryDSL, and is not the only bug in its support for EclipseLink cursors. See https://github.com/querydsl/querydsl/pull/2335.

**Comment by NiklasMehner** [comment]
ok, thanks. I will try to get this fixed in querydsl.
