### ISSUE TITLE
Bug: Oracle positional parameters with ParameterMode.REF_CURSOR out parameter

### ISSUE THREAD

**Issue by rfelcman** [eclipse-ee4j/eclipselink#618]
EclipseLink throw exception during a call of Oracle DB stored procedure with signature like this:
`PROCEDURE GetEmpIdFNameLNameFromRS(in_param IN INTEGER, p_recordset OUT SYS_REFCURSOR) AS`
It happens only if input parameter is passed via position e.g.
`spq.setParameter(1, 1);`
If input parameter is passed via name like:
`spq.setParameter("in_param", 1);`
it works OK.
I think, that this issue is related with #512 .
There is attached retest application to simulate this error. DB object creation is disabled there, but there is attached _init.sql_ script to create required DB objects.
Main test code is in the following methods
`com.oracle.jpa.bugtest.TestBug#bugTestNamedParam` - OK

`com.oracle.jpa.bugtest.TestBug#bugTestPositionParam` - throws Exception

[jpa-bug-EJB_FailedToUseStoredprocedureQuery.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/3880273/jpa-bug-EJB_FailedToUseStoredprocedureQuery.tar.gz)

As I checked this kind of call (positional parameters + `ParameterMode.REF_CURSOR`) declared via entity annotation `@NamedStoredProcedureQuery` is not tested in EclipseLink now.

Error stack:
```
javax.persistence.PersistenceException: java.lang.IllegalArgumentException: Invalid output parameter name : 2. operation not allowed: Ordinal binding and Named binding cannot be combined!

	at org.eclipse.persistence.internal.jpa.StoredProcedureQueryImpl.getResultList(StoredProcedureQueryImpl.java:589)
	at com.oracle.jpa.bugtest.TestBug.bugTestPositionParam(TestBug.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at 
...
...
Caused by: java.lang.IllegalArgumentException: Invalid output parameter name : 2. operation not allowed: Ordinal binding and Named binding cannot be combined!
	at org.eclipse.persistence.internal.jpa.StoredProcedureQueryImpl.getOutputParameterValue(StoredProcedureQueryImpl.java:523)
	at org.eclipse.persistence.internal.jpa.StoredProcedureQueryImpl.getResultList(StoredProcedureQueryImpl.java:560)
	... 40 more
Caused by: java.sql.SQLException: operation not allowed: Ordinal binding and Named binding cannot be combined!
	at oracle.jdbc.driver.OracleCallableStatement.getObject(OracleCallableStatement.java:3269)
	at oracle.jdbc.driver.OracleCallableStatementWrapper.getObject(OracleCallableStatementWrapper.java:978)
	at org.eclipse.persistence.internal.jpa.StoredProcedureQueryImpl.getOutputParameterValue(StoredProcedureQueryImpl.java:515)
	... 41 more
```

**Comment by dazey3** [comment]
Thanks for uncovering this issue and coming up with a fix! Unfortunately, this is a regression of #512 :( 
The issue seems to be that `StoredProcedureQueryImpl.getResultList()` and `StoredProcedureQueryImpl.getSingleResult()` have always explicitly called `StoredProcedureQueryImpl.getOutputParameterValue(String parameterName)`. #512 changed the implementation of `getOutputParameterValue(String parameterName)` to NOT translate the string -> index, but to instead just use the parameter name directly on the CallableStatement! 

That works fine for applications that are calling `getOutputParameterValue(String parameterName)` directly; it's on them to make sure they dont mix indexes and named parameters. Unfortunately, that doesn't work so well for `StoredProcedureQueryImpl.getResultList()` and `StoredProcedureQueryImpl.getSingleResult()`, where WE have to know what type to use (index or String).
