### ISSUE TITLE
ReadAllQuery fails in checkPrepare due to NullPointerException

### ISSUE THREAD

**Issue by seelenfaenger** [eclipse-ee4j/eclipselink#639]
I am developing a multitenancy enabled application. The multitenancy is schema based. Frameworks used so far are eclipselink 2.7.5, Spring data jpa 2.2.0.RELEASE and PostgreSQL. Creating, finding and deleting single entities works fine so far. A simple "findAll" works as well. However I have a problem with custom repository methods.

One entity is defined like this:

```java
@Entity
@Table(name = "CLAWDITE_HISTORY")
@Multitenant(MultitenantType.TABLE_PER_TENANT)
@TenantTableDiscriminator(type = TenantTableDiscriminatorType.SCHEMA, contextProperty = PersistenceUnitProperties.MULTITENANT_PROPERTY_DEFAULT)
@IdClass(SimpleLongId.class)
public class History implements Serializable {
	@Id
	@TableGenerator(name = "TABLE_GEN_HIST",
			table = "SEQUENCE_TABLE",
			pkColumnName = "SEQ_NAME",
			valueColumnName = "SEQ_COUNT",
			pkColumnValue = "HIST_SEQ")
	@GeneratedValue(strategy = GenerationType.AUTO)
	Long id;

	@Column(nullable = false)
	Long fkParentId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = true)
	private Date lastrun;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = false)
	private Date startDateTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = true)
	private Date endDateTime;

	@Column
	private String status;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = false)
	private Date modified;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(nullable = false)
	private Date created;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "history", cascade = CascadeType.ALL)
	@JoinColumns({
			@JoinColumn(name = "HISTORY_ID", referencedColumnName = "HISTORY_ID", nullable = false)})
	@CascadeOnDelete
	List<HistoryRecord> entries;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getLastrun() {
		return lastrun;
	}

	public void setLastrun(Date lastrun) {
		this.lastrun = lastrun;
	}

	public Date getStartDateTime() {
		return startDateTime;
	}

	public void setStartDateTime(Date startDateTime) {
		this.startDateTime = startDateTime;
	}

	public Date getEndDateTime() {
		return endDateTime;
	}

	public void setEndDateTime(Date endDateTime) {
		this.endDateTime = endDateTime;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getModified() {
		return modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public List<HistoryRecord> getEntries() {
		return entries;
	}

	public void setEntries(List<HistoryRecord> entries) {
		this.entries = entries;
	}

	public Long getFkParentId() {
		return fkParentId;
	}

	public void setFkParentId(Long fkParentId) {
		this.fkParentId = fkParentId;
	}

	@PrePersist
	public void prePersist() {
		Date now = new Date();
		created = now;
		modified = now;
	}

	@PreUpdate
	public void preUpdate() {
		modified = new Date();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id: ").append(getId());
		sb.append(", parentId: ").append(getFkParentId());
		sb.append(", created: ").append(getCreated());
		sb.append(", modified: ").append(getModified());
		sb.append(", startDateTime: ").append(getStartDateTime());
		sb.append(", endDateTime: ").append(getEndDateTime());
		sb.append(", Status: ").append(getStatus());
		return sb.toString();
	}
}
```
As I want to be able to find all History entities by the field fkParentId I created an additional method in the repository:
```java
@Query(value = "SELECT h FROM History h WHERE h.fkParentId = :fkParentId", nativeQuery = true)
public List<History> findAllByFkParentId(@Param("fkParentId") Long fkParentId);
```
Regardles if I simply use only the method name or add the Query annotation I end up with the following stacktrace:
```
[EL Finest]: query: 2019-12-04 16:23:16.73--UnitOfWork(2097614581)--Thread(Thread[main,5,main])--Execute query ReadAllQuery(referenceClass=History sql="SELECT h FROM History h WHERE h.fkParentId = :fkParentId")
[EL Warning]: 2019-12-04 16:23:16.741--UnitOfWork(2097614581)--Thread(Thread[main,5,main])--Local Exception Stack: 
Exception [EclipseLink-6168] (Eclipse Persistence Services - 2.7.5.v20191016-ea124dd158): org.eclipse.persistence.exceptions.QueryException
Exception Description: Query failed to prepare, unexpected error occurred: [java.lang.NullPointerException].
Internal Exception: java.lang.NullPointerException
Query: ReadAllQuery(referenceClass=History sql="SELECT h FROM History h WHERE h.fkParentId = :fkParentId")
    at org.eclipse.persistence.exceptions.QueryException.prepareFailed(QueryException.java:1598)
    at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:692)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:968)
...
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.NullPointerException
    at org.eclipse.persistence.internal.helper.NonSynchronizedVector.addAll(NonSynchronizedVector.java:315)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.getSelectionFields(ObjectLevelReadQuery.java:1808)
...
```
Debugging to the place where the exception is thrown shows me that in the RelationalDescriptor which appears to be used for the "getAllSelectionFields" the property allSelectionFields is null which causes the NullpointerException.

Thank you and kind regards

**Comment by rfelcman** [comment]
Hello, in the attachment You can find  my retest application to simulate this bug. It passing now, but I'd like ask You for some additional details:

1. More details about persistence properties used in _persistence.xml_ file. Mainly properties related with multitenancy.
2. About `@Query(value = "SELECT h FROM History h WHERE h.fkParentId = :fkParentId", nativeQuery = true)` as I understand this is Spring not JPA annotation. `nativeQuery = true` means that query is passed to DB as it. I mean in JPA something like `Query query = em.createNativeQuery(` is used. If yes is it right table name used there? There should be something like `SELECT h FROM <schema>.CLAWDITE_HISTORY h.... `.

Feel free to check and modify retest application with persistence properties and query mentioned above. There is _init.sql_ script used to prepare DB schema and table. Testing code is located at `com.oracle.jpa.bugtest.TestBug` mainly methods `testQuery(...)`, `testNativeQueryPositional(...)`, `testNativeQueryNaming(...)`

[jpa-bug-639-ReadAllQueryFails.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/4655742/jpa-bug-639-ReadAllQueryFails.tar.gz
)

**Comment by rfelcman** [comment]
Due a missing response for my latest comment (8 months old) I'm closing this bug now.
In cases of new details feel free to reopen this bug.
