### ISSUE TITLE
Is it a bug in the documentation or in the code? Problem when querying a multitenant entity

### ISSUE THREAD

**Issue by rlagoue** [eclipse-ee4j/eclipselink#701]
I am developing a multitenancy enabled application. The multitenancy is of type "single_table" based. 

The "EntityManagerFactory" is shared in this environment. For each request a new instance of EntityManager is created.

When I set the property "multitenant.tenants-share-cache" to "true" in the persistence.xml, and perform a fetch a multitenant entity by id, then i receive the the following exception:
`Exception Description: No value was provided for the session property [eclipselink.tenant-id]. This exception is possible when using additional criteria or tenant discriminator columns without specifying the associated contextual property. These properties must be set through EntityManager, EntityManagerFactory or persistence unit properties. If using native EclipseLink, these properties should be set directly on the session.
Query: ReadObjectQuery`

With the stack trace 
`at org.eclipse.persistence.exceptions.QueryException.missingContextPropertyForPropertyParameterExpression(QueryException.java:268) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.expressions.ParameterExpression.getValue(ParameterExpression.java:279) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseCall.translate(DatabaseCall.java:1148) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:274) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectOneRow(DatasourceCallQueryMechanism.java:764) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRowFromTable(ExpressionQueryMechanism.java:2822) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectOneRow(ExpressionQueryMechanism.java:2775) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ReadObjectQuery.executeObjectLevelReadQuery(ReadObjectQuery.java:561) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1232) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1191) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ReadObjectQuery.execute(ReadObjectQuery.java:447) ~[org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.internalExecuteQuery(AbstractSession.java:3356) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.valueFromQuery(NoIndirectionPolicy.java:328) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.valueFromRowInternal(ForeignReferenceMapping.java:2340) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.mappings.OneToOneMapping.valueFromRowInternal(OneToOneMapping.java:1850) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.valueFromRow(ForeignReferenceMapping.java:2184) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.readFromRowIntoObject(ForeignReferenceMapping.java:1510) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildAttributesIntoObject(ObjectBuilder.java:472) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:1015) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildWorkingCopyCloneFromRow(ObjectBuilder.java:2250) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObjectInUnitOfWork(ObjectBuilder.java:858) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:745) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildObject(ObjectBuilder.java:699) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.buildObject(ObjectLevelReadQuery.java:861) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ReadAllQuery.registerResultInUnitOfWork(ReadAllQuery.java:987) [org.eclipse.persistence.core-2.7.5.jar:?]
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:598) [org.eclipse.persistence.core-2.7.5.jar:?]`

I want the object to be shared in the L2 cache, since instance of this entity are expected to remain alchange 80% of the time.

My decision to set the property "multitenant.tenants-share-cache" to "true" is based on the documentation from this  [link](https://www.eclipse.org/eclipselink/documentation/2.4/jpa/extensions/p_multitenant_tenants-share-cache.htm)

The property eclipselink is not seeing "eclipselink.tenant-id" is set on each new EntityManager immediately after creation. 

I looked a little bit into the eclipselink source code, and my investigation lead me to this piece of code (in class org.eclipse.persistence.internal.expressions.ParameterExpression):
![image](https://user-images.githubusercontent.com/5127870/73559835-1fd2b400-4456-11ea-9d7d-aba1171c7dee.png)

Line 279 is the where it is decided to throw the exception, about the missing property. But few line above (line 272 - 276), the code is trying only to check the presence of the property on the session (in JPA EntityManagerFactory), when the property is set on the EntityManager as can be seen on the following screenshot

![image](https://user-images.githubusercontent.com/5127870/73560357-0f6f0900-4457-11ea-9913-b17f357905bc.png)

According to the document [here](https://www.eclipse.org/eclipselink/documentation/2.4/jpa/extensions/p_multitenant_tenants-share-cache.htm), the property "multitenant.tenants-share-cache" should be set to true to inform eclipse about the fact that the multitenant entity will be L2-cached.  Letting this property to false, may cause queries that use the cache may return data from other tenants when using the PROTECTED setting.

When I set the property to false everything works without a problem.

Is it a bug in the documentation or in the code?

**Comment by rfelcman** [comment]
Hello,

I created some test case (see attached Maven project) to simulate this bug but without success (without error).
If You want try it in the `persistence.xml` choose and modify any prefered DB connection.
Application will create test table automaticaly by JPA property 
`<property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>`, 
but You can disable it and create DB table manually by SQL command from `init.sql` script.
Test entity is `com.oracle.jpa.bugtest.domain.TestEntity`.
Test code (JUnit test) is `com.oracle.jpa.bugtest.TestBug`.
Together with this I'd like ask You for a more details about:
  - DB table structure (columns related with multitenancy)
  - `persistence.xml` file
  - Query which leads into error (standart, native, named query stored in the entity, how parameters - id is passed there)
Feel free to modify attached test case and sent it back.
[jpa-bug-701-QueryingMultitenantEntity.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/4393893/jpa-bug-701-QueryingMultitenantEntity.tar.gz)

**Comment by rfelcman** [comment]
Sorry, but there is no any response during previous 2 months. In case of additional/requested details feel free to reopen this bug.

**Comment by rlagoue** [comment]
Hello,

Thank you to care about this bug.
sorry didn't see the notification email. Let's dive in directly .

To your questions:
-  DB table structure: I have column on each multitenant capable entity
- persistence.xml: is it enough to just share the properties set inside?
-  Query leading  into error is "standard" 

However I have made some research since then. And I found out that this happens for sure in the  situation with the following specs:
-  you have 2 multitenant capable entities (let's name both A and B
- There is a relation OneToMany between both ( B has a reference to field of type A, whereas A has a list of objects of type B. B's side being the leading one. This means the relation on A side is mapped using "mapped by".)
-  don't forget to ensure that list of Bs in A is loaded lazily
- fetch an object of type A by id using a JPQL query
- attempt to access the list of objects of type B (to trigger the lazy load) -> This will trigger a standard query which will finish with the exception above.

**Comment by rlagoue** [comment]
I am not able to reopen this issue @rfelcman
