### ISSUE TITLE
NullPointerException while instantiating a JAXBContext

### ISSUE THREAD

**Issue by nepolean** [eclipse-ee4j/eclipselink#717]
Instantiating JAXBContext lead to NPE as shown below

`  private JAXBContext createJAXBContext(Class<?> cls) throws JAXBException {
    JAXBContext ctx = jaxbCtxCache.get(cls);
    if (Objects.isNull(ctx)) {
      ctx =  JAXBContext.newInstance(cls);
      jaxbCtxCache.put(cls, ctx);
    }
     System.out.println(ctx.getClass().getName());
    return ctx;
  }`

The above code results in NPE at 

`[java.lang.NullPointerException]
	at org.eclipse.persistence.jaxb.JAXBContext$TypeMappingInfoInput.createContextState(JAXBContext.java:1163)
	at org.eclipse.persistence.jaxb.JAXBContext.<init>(JAXBContext.java:198)
	at org.eclipse.persistence.jaxb.JAXBContextFactory.createContext(JAXBContextFactory.java:167)
	at org.eclipse.persistence.jaxb.JAXBContextFactory.createContext(JAXBContextFactory.java:154)
	at org.eclipse.persistence.jaxb.JAXBContextFactory.createContext(JAXBContextFactory.java:114)
	at org.eclipse.persistence.jaxb.JAXBContextFactory.createContext(JAXBContextFactory.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:251)
	at `javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)`
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:345)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)`

and apparently the original line of code which caused the NPE is this.

`Caused by: java.lang.NullPointerException
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.updateGlobalElements(AnnotationsProcessor.java:4031)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.postBuildTypeInfo(AnnotationsProcessor.java:777)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.processReferencedClass(AnnotationsProcessor.java:900)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.buildTypeInfo(AnnotationsProcessor.java:863)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.findAndProcessObjectFactory(AnnotationsProcessor.java:3786)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.findAndProcessObjectFactory(AnnotationsProcessor.java:3772)
	at org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor.buildNewProperty(AnnotationsProcessor.java:2047)
`

**Comment by rfelcman** [comment]
Sorry but could You please provide some functional test case based on:
```
private JAXBContext createJAXBContext(Class<?> cls) throws JAXBException {
  JAXBContext ctx = jaxbCtxCache.get(cls);
  if (Objects.isNull(ctx)) {
    ctx = JAXBContext.newInstance(cls);
    jaxbCtxCache.put(cls, ctx);
  }
  System.out.println(ctx.getClass().getName()); return ctx;
}
```
Is it `cls` always not `null`.

**Comment by rfelcman** [comment]
Sorry there is no any response yet. I'm closing this bug now. Feel free to reopen it if requested details are available.
