### ISSUE TITLE
getResultList() not returning Tuple

### ISSUE THREAD

**Issue by Haaramo** [eclipse-ee4j/eclipselink#778]
```
List<javax.persistence.Tuple> result = entityManager.createQuery("select f.Id as Id, f.Project as Project from FirewallRequest f", javax.persistence.Tuple.class)
                                                    .getResultList();
result.get(0).get("Project");
```
causes

`java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class javax.persistence.Tuple ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; javax.persistence.Tuple is in unnamed module of loader java.net.URLClassLoader @7a9273a8)`

I have seen a lot of examples showing this should return key/value pairs in Tuple class, for example here: https://stackoverflow.com/a/59840498/1827453

**Comment by demanzano** [comment]
Hi,

I'm experiencing the same problem, using EclipseLink v. 2.7.6.payara-p1   in Payara 5.2020.3

No one else uses Tuple with EclipseLink ? ;-)

Ale

**Comment by smillidge** [comment]
Does anyone have a simple executable  test case that demonstrates the issue?

**Comment by OndroMih** [comment]
The JPA specification doesn't require that this is supported and, unfortunately, EclipseLink doesn't support this while Hibernate does. However, this seems to be very useful and reasonable to implement as an enhancement to ElcipseLink on top of what JPA requires.

The `Tuple` class is part of the JPA Criteria API and is not meant to be used in JPQL queries (at least this isn't specified yet).

Javadoc of `EntityManager.createQuery` explicitly says: 

> The select list of the query must contain only a single item, which must be assignable to the type specified by the resultClass argument.

with this note:

>The semantics of this method may be extended in a future release of this specification to support other result types. Applications
that specify other result types (e.g., Tuple.class) will not be portable.

It means that EclipseLink is not required to support the behavior requested in this issue. So it's not a bug rather a missing feature that should be implemented to support what Hibernate already supports.

**Comment by demanzano** [comment]
Thanks for the detailed analysis, indeed it would be very very useful ! Tuple.class is already supported for Criteria queries so would be coherent to have it for JPQL queries too..

**Comment by quaff** [comment]
The exception is different now.

```
Caused by: Exception [EclipseLink-6007] (Eclipse Persistence Services - 3.0.4.v202310250740): org.eclipse.persistence.exceptions.QueryException
Exception Description: Missing descriptor for [interface jakarta.persistence.Tuple].
Query: ReadAllQuery(referenceClass=Tuple sql="select * from test_entity")
	at org.eclipse.persistence.exceptions.QueryException.descriptorIsMissing(QueryException.java:480)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkDescriptor(ObjectLevelReadQuery.java:890)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:834)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1195)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:485)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1283)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3025)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1844)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1826)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1791)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:262)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:482)
	... 4 more
```
