### ISSUE TITLE
@Array annotated empty or null Java collection results in PSQLException

### ISSUE THREAD

**Issue by davidjayb** [eclipse-ee4j/eclipselink#790]
Description: When defining an entity with an `@Array` field, if that field is empty or null then PostgreSQL will throw an exception that the incorrect type was used and needs to be cast. This looks to have come about as a result of a bug fix in the pgjdbc driver. I believe Eclipselink needs address using the correct type information when persisting null array database types.

Related bug reported in the bugzilla bug tracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545557

java 1.8
eclipselink 2.7.6
pgjdbc 42.2.4

Changelog for pgjdbc: https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.4
PR for related change: https://github.com/pgjdbc/pgjdbc/pull/1160/

Example entity
```
@Entity
@Table(name = "data")
@Struct(name = "some_list", fields = {"some_list"})
@Converter(name = UuidConverter.name, converterClass = UuidConverter.class)
public class Data {

    @Id
    @Column(name = "ID", columnDefinition = "uuid")
    @Convert(UuidConverter.name)
    private UUID id;

    @Column(name = "SOME_LIST")
    @Array(databaseType = "varchar", targetClass = String.class)
    private List<String> someList = new LinkedList<>();
}
```

Resulting stack trace
```
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: column "some_list" is of type character varying[] but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 211
Error Code: 0
Call: INSERT INTO DATA (ID, SOME_LIST) VALUES (?, ?)
	bind => [4db87efd-0b5f-4bc4-b9f4-35d1781fac70, null]
Query: InsertObjectQuery(Data{id=4db87efd-0b5f-4bc4-b9f4-35d1781fac70})
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1650)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:906)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2099)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:275)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:261)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:411)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:167)
	at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:182)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:504)
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:82)
	at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:92)
	at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:316)
	at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:60)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:110)
	at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:87)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2983)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:229)
	at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:128)
	at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4398)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1495)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1641)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:457)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:975)
	... 28 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "some_list" is of type character varying[] but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 211
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
	... 58 more
```

**Comment by lukasj** [comment]
I believe something like this has been fixed already, can you check [2.7.7-RC1](https://www.eclipse.org/lists/eclipselink-users/msg08764.html), please?

**Comment by davidjayb** [comment]
2.7.7-RC1 looks to have solved the issue +1 what is the process for eclipselink releases being promoted from RC to GA?

**Comment by lukasj** [comment]
generally we try to have at least a day between RC and final build. At this point we're planning the final build to happen on Thu, May 7 (or better as soon as the infra allows us to create final bits after Thu)

**Comment by davidjayb** [comment]
Děkuju Lukas :-)
