### ISSUE TITLE
JPA Left Join Fetch on Embeddable ElementColection fails

### ISSUE THREAD

**Issue by Cousjava** [eclipse-ee4j/eclipselink#921]
Calling left_fetch on an embeddable elementCollection of entities fails. 

Reproducer attached, go to rest/test/failnamed to get
`org.eclipse.persistence.exceptions.ValidationException
Exception Description: The aggregate object [class be.rubus.payara.support.ticket1455.model.Tag] cannot be directly registered in the UnitOfWork.  It must be associated with the source (owner) object.
	at org.eclipse.persistence.exceptions.ValidationException.cannotRegisterAggregateObjectInUnitOfWork(ValidationException.java:622)`

The equivalent SQL query of `SELECT t1.ID, t1.BODY, t1.TITLE, t0.TAGTEXT FROM BLOGPOST t1 LEFT OUTER JOIN BlogPost_TAGS t0 ON (t0.BlogPost_ID = t1.ID)` called directly on the database works.

This bugs occurs with both 2.7 Eclipselink on Payara with H2DB and 3.0 Eclipselink on GlassFish with derby.

[fish-406.zip](https://github.com/eclipse-ee4j/eclipselink/files/5383830/fish-406.zip)

**Comment by Cousjava** [comment]
From debugging and a heap dump I found that there are two instances of RelationalDescriptor the are for the `Tag` class (the `@Embeddable` entity) in the reproducer, one of which has not had all its fields initialised, while the second one has. 

This gives rise to exceptions like `java.lang.NullPointerException at org.eclipse.persistence.internal.descriptors.InstanceVariableAttributeAccessor.getAttributeValueFromObject(InstanceVariableAttributeAccessor.java:83)
`
