### ISSUE TITLE
StackOverflowError in ObjectReferenceMapping

### ISSUE THREAD

**Issue by laeubi** [eclipse-ee4j/eclipselink#993]
See attached stacktrace, it seems this happens if the init fails or something goes wrong creating the object graph. Version used: 2.7.7.v20200504-69f2c2b80d

```
java.lang.StackOverflowError
	at org.eclipse.persistence.internal.descriptors.InstantiationPolicy.buildNewInstance(InstantiationPolicy.java:115)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildNewInstance(ObjectBuilder.java:670)
	at org.eclipse.persistence.descriptors.copying.InstantiationCopyPolicy.buildClone(InstantiationCopyPolicy.java:33)
	at org.eclipse.persistence.descriptors.copying.AbstractCopyPolicy.buildWorkingCopyClone(AbstractCopyPolicy.java:45)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.instantiateWorkingCopyClone(ObjectBuilder.java:4026)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1058)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1006)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4066)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3995)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildUnitofWorkCloneForPartObject(ObjectReferenceMapping.java:136)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildCloneForPartObject(ObjectReferenceMapping.java:98)
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.cloneAttribute(NoIndirectionPolicy.java:81)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildClone(ForeignReferenceMapping.java:316)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.populateAttributesForClone(ObjectBuilder.java:4181)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.populateAndRegisterObject(UnitOfWorkImpl.java:3774)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1077)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1006)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4066)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3995)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildUnitofWorkCloneForPartObject(ObjectReferenceMapping.java:136)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildCloneForPartObject(ObjectReferenceMapping.java:98)
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.cloneAttribute(NoIndirectionPolicy.java:81)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildClone(ForeignReferenceMapping.java:316)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.populateAttributesForClone(ObjectBuilder.java:4181)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.populateAndRegisterObject(UnitOfWorkImpl.java:3774)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1077)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1006)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4066)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3995)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildUnitofWorkCloneForPartObject(ObjectReferenceMapping.java:136)
```

**Comment by laeubi** [comment]
This might be related to #992

**Comment by laeubi** [comment]
Just another place where this happens, strange enough it seems to try to only log a message at that place...

```
java.lang.StackOverflowError
	at org.eclipse.persistence.logging.DefaultSessionLog.getLevel(DefaultSessionLog.java:90)
	at org.eclipse.persistence.logging.DefaultSessionLog.shouldLog(DefaultSessionLog.java:110)
	at org.eclipse.persistence.internal.sessions.AbstractSession.shouldLog(AbstractSession.java:4713)
	at org.eclipse.persistence.internal.sessions.AbstractSession.log(AbstractSession.java:4758)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.logDebugMessage(UnitOfWorkImpl.java:5729)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4025)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3995)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildUnitofWorkCloneForPartObject(ObjectReferenceMapping.java:136)
	at org.eclipse.persistence.mappings.ObjectReferenceMapping.buildCloneForPartObject(ObjectReferenceMapping.java:98)
	at org.eclipse.persistence.internal.indirection.NoIndirectionPolicy.cloneAttribute(NoIndirectionPolicy.java:81)
	at org.eclipse.persistence.mappings.ForeignReferenceMapping.buildClone(ForeignReferenceMapping.java:316)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.populateAttributesForClone(ObjectBuilder.java:4181)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.populateAndRegisterObject(UnitOfWorkImpl.java:3774)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1077)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.cloneAndRegisterObject(UnitOfWorkImpl.java:1006)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:4066)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3995)
```

**Comment by laeubi** [comment]
The problem seem to occur when I try to access a mapped collection of the object in the database.

**Comment by laeubi** [comment]
I was able to circumvent the problem while playing around with different settings I was able to produce the follwoing error to pe printed to the log:

IllegalAccessError: Update to non-static final field Item.children attempted from a different method (_persistence_set) than the initializer method <init> 

I have removed the final flag and the error went away
Code for reproduction:
```
  @OneToMany(mappedBy = "parent", fetch = FetchType.LAZY)
    private final Set<Item> children = new HashSet<Item>();
```

No idea why this cause StackOverflow instead of an error in the above cases.

**Comment by rfelcman** [comment]
It looks like, that is related with cyclic relation between entities, but could You please provide there all/booth entities which participates in object graph.
Another thing is, when it's happen? I mean which JPA operation leads into error? Like `em.find(...), merge(...)....`
Any test case should be great.

**Comment by laeubi** [comment]
The problem occurs in a larger Object Relation Mapping when I try to access the mapped child, I think it would be possible to use any entity that has a @OneToMany, and make the field final like in the example:

```
 @OneToMany(mappedBy = "parent", fetch = FetchType.LAZY)
 private final Set<Item> children = new HashSet<Item>();
```

As it has occurred when upgrading from Java 6 > Java 11 it seems that there has changed something between java versions that allow to update final fields? As soon as I remove the final modifier the problem does not occur anymore.

**Comment by rfelcman** [comment]
I created test application to simulate this issue but without success. See attached archive.
[jpa-bug-993-StackOverflowErrorInObjectReferenceMapping.tar.gz](https://github.com/eclipse-ee4j/eclipselink/files/5770309/jpa-bug-993-StackOverflowErrorInObjectReferenceMapping.tar.gz)
 
There are two test entities `com.oracle.jpa.bugtest.domain.TestEntityMaster` and `com.oracle.jpa.bugtest.domain.TestEntityDetail` and master has following field
```
@OneToMany(mappedBy = "master", fetch = FetchType.LAZY)
private final Set<TestEntityDetail> details = new HashSet<>();
```
but test `com.oracle.jpa.bugtest.TestBug#findTest()` will pass without any error.
Environment is Java 11, MySQL, EclipseLink 2.7.7.
DB Initialization script is `init.sql`

But I noticed in Your previous comment following

> .... different method (_persistence_set) than ....

`_persistence_set` should be related with JPA Weaving.
https://www.eclipse.org/eclipselink/documentation/2.7/concepts/app_dev005.htm#CCHJEDFH
Is it after migration weaving enabled?
Is it possible to put there complete error stack trace?

**Comment by laeubi** [comment]
Yes weaving was enabled.
If i remember right I played around with different settings (and maybe also with weaving) so probably I got the stackoverflow with weaving enabled and without the error about illegal access.
